(function(root){
  'use strict';const ns=root.OmniPerformanceScale;const engine=ns.PerformanceScaleEngine.create({provider:{readSnapshot:async()=>({memory:{},database:{},realtime:{},cache:{},assets:[],network:{},cpuUsage:0,storageBytes:0})}});
  const esc=v=>String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const row=(a,b)=>`<div class="performance-scale-row"><span>${esc(a)}</span><strong>${esc(typeof b==='object'?JSON.stringify(b):b)}</strong></div>`;const title=x=>`<div class="table-title">${esc(x)}</div>`;
  const notice=()=>'<div class="alert alert-info"><strong>Performance & Scale — Read-only Simulation.</strong> لا يتم تغيير Business Logic أو تشغيل SQL أو فتح Connections أو تخصيص مليون سجل.</div>';const out=()=>'<pre class="performance-scale-result">No performance simulation has run.</pre>';
  function dashboard(){const s=engine.snapshot();return `${notice()}<div class="performance-scale-actions"><button class="btn btn-outline btn-sm" onclick="refreshPerformanceScale()">Refresh Metrics Snapshot</button><button class="btn btn-outline btn-sm" onclick="runScaleStressPreview()">Run 100K / 1M Simulation</button></div><div class="performance-scale-grid"><div class="report-card">${title('Memory')}${row('Usage',`${s.memory.usagePercent}%`)}</div><div class="report-card">${title('CPU Preview')}${row('Usage',`${s.cpu.usage}%`)}</div><div class="report-card">${title('Storage')}${row('Bytes',s.storage.estimatedBytes)}</div><div class="report-card">${title('Realtime')}${row('Health',s.realtime.health)}</div><div class="report-card">${title('Cache')}${row('Hit Rate',`${s.cache.hitRate}%`)}</div><div class="report-card">${title('Network')}${row('Pending',s.network.pending)}</div></div><div class="report-card" style="margin-top:14px">${title('Reports')}${ns.PerformanceReportBuilder.TYPES.map(t=>`<button class="btn btn-outline btn-sm" style="margin:4px" onclick="previewPerformanceReport('${t}')">${esc(t)} Report</button>`).join('')}</div>${out()}`;}
  function memory(){const m=engine.snapshot().memory;return `${notice()}<div class="report-card">${title('Memory Usage')}${row('Used Bytes',m.usedBytes)}${row('Limit Bytes',m.limitBytes)}${row('Usage',`${m.usagePercent}%`)}${row('Memory Snapshots',m.memorySnapshots.length)}${row('Large Objects',m.largeObjects.length)}${row('Leak Detector',m.leakDetectorPreview)}${row('Garbage Collection Hints',m.garbageCollectionHints)}${row('GC Triggered','No')}</div>${out()}`;}
  function cpu(){return `${notice()}<div class="report-card">${title('CPU Usage Preview')}${row('Usage',`${engine.snapshot().cpu.usage}%`)}${row('Background Workers',ns.BackgroundWorkerPreview.plan('aggregation',100000))}${row('Workers Started','0')}</div>${out()}`;}
  function storage(){const s=engine.snapshot();return `${notice()}<div class="performance-scale-grid"><div class="report-card">${title('Storage Analyzer')}${row('Estimated Bytes',s.storage.estimatedBytes)}</div><div class="report-card">${title('Bundle Analyzer')}${row('Total Bytes',s.bundle.totalBytes)}${row('Compressed',s.bundle.compressedBytes)}${row('Lazy Candidates',s.bundle.lazyCandidates)}</div><div class="report-card">${title('Asset Optimization Preview')}${row('Recommendations',s.bundle.recommendations)}</div></div>${out()}`;}
  function dataset(){const preview=engine.stressPreview({products:100000,transactions:1000000});return `${notice()}<div class="report-card">${title('Large Dataset Analyzer')}${row('100K Products',preview.products)}${row('1M Transactions Preview',preview.transactions)}${row('Virtual Scroll Window',preview.virtualWindow)}${row('Chunked Rendering',preview.productChunks)}${row('Pagination Engine',preview.transactionPages)}${row('Records Allocated',preview.recordsAllocated)}${row('Transactions Executed',preview.transactionsExecuted)}</div>${out()}`;}
  function query(){const d=engine.snapshot().database;return `${notice()}<div class="report-card">${title('Query Performance Preview')}${row('Slow Query Detector',d.slowQueries.length)}${row('Large Table Analyzer',d.largeTables.length)}${row('Index Recommendation Preview',d.indexRecommendations)}${row('Storage Estimation',d.storageEstimateBytes)}${row('Connection Pool Preview',d.connectionPoolPreview)}${row('Repository Profiler',d.repositoryProfile)}${row('SQL Executed',d.sqlExecuted)}</div>${out()}`;}
  function realtime(){const r=engine.snapshot().realtime;return `${notice()}<div class="report-card">${title('Realtime Status')}${row('Health',r.health)}${row('Connected',r.connected)}${row('Latency',`${r.latencyMs} ms`)}${row('Connection Monitor','Snapshot only')}${row('Reconnect Strategy Preview',r.reconnectStrategy)}${row('Offline Queue Monitor',r.offlineQueue)}${row('Sync Latency',`${r.syncLatencyMs} ms`)}${row('Connections Opened',r.connectionsOpened)}</div>${out()}`;}
  function cache(){const c=engine.snapshot().cache;return `${notice()}<div class="report-card">${title('Cache Status')}${Object.entries(c).map(([k,v])=>row(k,v)).join('')}</div>${out()}`;}
  function network(){const n=engine.snapshot().network;return `${notice()}<div class="report-card">${title('Network Status & Request Queue Preview')}${Object.entries(n).map(([k,v])=>row(k,v)).join('')}</div>${out()}`;}
  function lazy(){const l=engine.lazyPlan({moduleChunks:['reports','analytics']});return `${notice()}<div class="performance-scale-grid"><div class="report-card">${title('Lazy Loading Status')}${row('Strategy',l.strategy)}${row('Images',l.imageAttribute)}${row('Activated',l.activated)}</div><div class="report-card">${title('Virtual Scrolling')}${row('100K Window',engine.virtualWindow({totalItems:100000,itemHeight:40,viewportHeight:600}))}</div><div class="report-card">${title('Chunked Rendering')}${row('Plan',engine.chunkPlan(100000,1000))}</div><div class="report-card">${title('Pagination')}${row('1M Preview',engine.page(1000000,1,100))}</div></div>${out()}`;}
  function content(v){if(v==='memory-usage')return memory();if(v==='cpu-usage')return cpu();if(v==='storage-analyzer')return storage();if(v==='large-dataset-analyzer')return dataset();if(v==='query-performance')return query();if(v==='realtime-status')return realtime();if(v==='cache-status')return cache();if(v==='network-status')return network();if(v==='lazy-loading-status')return lazy();return dashboard();}
  function renderPerformanceScalePage(view){const target=document.getElementById(`performance-scale-${view}`);if(target)target.innerHTML=content(view);}function output(v){const target=document.querySelector('.page.active .performance-scale-result');if(target)target.textContent=JSON.stringify(v,null,2);}
  async function refreshPerformanceScale(){try{const v=await engine.refresh();renderPerformanceScalePage(document.querySelector('.page.active').id.replace('page-performance-scale-',''));output(v);return v;}catch(e){output({error:String(e.message||e)});}}
  function runScaleStressPreview(){const v=engine.stressPreview({products:100000,transactions:1000000});output(v);return v;}function previewPerformanceReport(type){const v=engine.report(type);output(v);return v;}
  Object.assign(root,{renderPerformanceScalePage,refreshPerformanceScale,runScaleStressPreview,previewPerformanceReport});root.OmniPerformanceScaleUi=Object.freeze({version:'1.0.0',engine});
})(typeof globalThis!=='undefined'?globalThis:window);
