(function(root){
  'use strict';const ns=root.OmniPerformanceScale=root.OmniPerformanceScale||{};
  function create(options){options=options||{};let state={memory:ns.MemoryProfiler.analyze(),database:ns.DatabasePerformanceAnalyzer.analyze(),realtime:ns.RealtimePerformanceMonitor.analyze(),cache:ns.CacheStatistics.calculate(),bundle:ns.BundleAssetAnalyzer.analyze(),network:ns.RequestQueuePreview.analyze(),cpu:Object.freeze({usage:0,preview:true}),storage:Object.freeze({estimatedBytes:0}),loadedAt:null};const snapshot=()=>Object.freeze({...state,readOnly:true});
    async function refresh(){if(!options.provider||typeof options.provider.readSnapshot!=='function')throw new Error('READ_ONLY_PERFORMANCE_PROVIDER_REQUIRED');const raw=await options.provider.readSnapshot();state={memory:ns.MemoryProfiler.analyze(raw.memory),database:ns.DatabasePerformanceAnalyzer.analyze(raw.database),realtime:ns.RealtimePerformanceMonitor.analyze(raw.realtime),cache:ns.CacheStatistics.calculate(raw.cache),bundle:ns.BundleAssetAnalyzer.analyze(raw.assets),network:ns.RequestQueuePreview.analyze(raw.network),cpu:Object.freeze({usage:Math.max(0,Math.min(100,Number(raw.cpuUsage||0))),preview:true}),storage:Object.freeze({estimatedBytes:Number(raw.storageBytes||0)}),loadedAt:new Date().toISOString()};return snapshot();}
    function stressPreview(input){input=input||{};const products=Math.max(0,Number(input.products||100000)),transactions=Math.max(0,Number(input.transactions||1000000));return Object.freeze({products,transactions,virtualWindow:ns.VirtualScrollEngine.windowFor({totalItems:products,itemHeight:40,viewportHeight:600}),productChunks:ns.ChunkedRenderingEngine.plan(products,1000),transactionPages:ns.PaginationEngine.page(transactions,1,100),workerPlan:ns.BackgroundWorkerPreview.plan('aggregation',transactions),recordsAllocated:0,transactionsExecuted:0,simulationOnly:true});}
    return Object.freeze({refresh,snapshot,stressPreview,virtualWindow:ns.VirtualScrollEngine.windowFor,lazyPlan:ns.LazyLoadingEngine.plan,chunkPlan:ns.ChunkedRenderingEngine.plan,page:ns.PaginationEngine.page,report:type=>ns.PerformanceReportBuilder.build(type,snapshot())});
  }
  ns.PerformanceScaleEngine=Object.freeze({version:'1.0.0',create});
})(typeof globalThis!=='undefined'?globalThis:window);
