(function(root){
  'use strict';const ns=root.OmniProductionExecution;let ownerSession=null;
  async function sessionProvider(){const client=typeof root.getSupabaseClient==='function'?root.getSupabaseClient():null;if(!client||!client.auth)return null;const sessionResult=await client.auth.getSession(),userResult=await client.auth.getUser(),session=sessionResult.data&&sessionResult.data.session,user=userResult.data&&userResult.data.user;if(!session||!user)return null;ownerSession={accessToken:session.access_token,userId:user.id,platformRole:user.app_metadata&&user.app_metadata.platform_role};return ownerSession;}
  const engine=ns.ProductionExecutionEngine.create();const esc=v=>String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const row=(a,b)=>`<div class="production-exec-row"><span>${esc(a)}</span><strong>${esc(typeof b==='object'?JSON.stringify(b):b)}</strong></div>`;const title=x=>`<div class="table-title">${esc(x)}</div>`;
  const warning=()=>`<div class="alert alert-danger"><strong>Controlled Production Execution.</strong> الوضع الافتراضي OFF. التنفيذ الحقيقي يتطلب ERP Owner، تفعيلًا server-side، وتأكيدًا مطابقًا لكل طلب.</div>`;const out=()=>'<pre class="production-exec-result">No production execution action has run.</pre>';
  function status(){const s=engine.snapshot();return `<div class="production-status ${s.mode.enabled?'enabled':'disabled'}">${s.mode.enabled?'🟢 PRODUCTION ON':'🔴 PRODUCTION OFF'}</div>${row('Server Enabled',s.mode.serverEnabled)}${row('Owner Verified',s.mode.ownerVerified)}${row('Gateway Configured',s.gateway.configured)}`;}
  function center(){const ops=ns.OperationRegistry.definitions.map(x=>`<option value="${x.id}">${esc(x.label)}</option>`).join('');const reports=[['execution','Execution Report'],['deployment','Deployment Report'],['provisioning','Provisioning Report'],['verification','Verification Report'],['rollback','Rollback Report']];return `${warning()}<div class="report-card">${title('Production Mode Configuration')}${status()}<div class="form-grid"><div class="form-group"><label>Production Edge Function URL</label><input id="productionEdgeUrl" autocomplete="off"></div><div class="form-group"><label>Anon Key</label><input id="productionAnonKey" type="password" autocomplete="off"></div></div><div class="production-exec-actions"><button class="btn btn-outline btn-sm" onclick="connectProductionExecution()">Validate Owner & Status</button><button class="btn btn-outline btn-sm" onclick="initializeProductionControlPlane()">Initialize Control Plane</button><button class="btn btn-danger btn-sm" onclick="toggleProductionMode(true)">Enable Production</button><button class="btn btn-outline btn-sm" onclick="toggleProductionMode(false)">Disable Production</button></div></div><div class="report-card" style="margin-top:14px">${title('Critical Operation')}<div class="form-grid"><div class="form-group"><label>Operation</label><select id="productionOperation">${ops}</select></div><div class="form-group"><label>Tenant ID</label><input id="productionTenantId"></div><div class="form-group"><label>Payload JSON</label><textarea id="productionPayload">{}</textarea></div></div><div class="production-exec-actions"><button class="btn btn-outline btn-sm" onclick="previewProductionExecution()">Preview</button><button class="btn btn-danger btn-sm" onclick="confirmAndExecuteProduction()">Confirm & Execute</button></div></div><div class="report-card" style="margin-top:14px">${title('Reports')}${reports.map(([type,label])=>`<button class="btn btn-outline btn-sm" style="margin:4px" onclick="previewProductionReport('${type}')">${label}</button>`).join('')}</div>${out()}`;}
  function queue(pendingOnly){const values=pendingOnly?engine.snapshot().pending:engine.snapshot().queue;return `${warning()}<div class="overflow-x"><table class="data-table"><thead><tr><th>Request</th><th>Operation</th><th>Tenant</th><th>Status</th><th>Attempts</th></tr></thead><tbody>${values.length?values.map(x=>`<tr><td>${esc(x.requestId)}</td><td>${esc(x.operation)}</td><td>${esc(x.tenantId)}</td><td>${esc(x.status)}</td><td>${x.attempts}</td></tr>`).join(''):'<tr><td colspan="5">No operations in this browser session.</td></tr>'}</tbody></table></div>${out()}`;}
  function history(){const values=engine.snapshot().history;return `${warning()}<div class="report-card">${title('Execution History')}${values.length?values.map(x=>row(x.requestId,`${x.item.operation} — ${x.verification.valid?'verified':'review'}`)).join(''):row('Status','No executions in this browser session')}</div>${out()}`;}
  function rollback(){return `${warning()}<div class="report-card">${title('Rollback Manager')}<div class="form-grid"><div class="form-group"><label>Execution ID</label><input id="rollbackExecutionId"></div><div class="form-group"><label>Rollback ID</label><input id="rollbackPointId"></div><div class="form-group"><label>Operation</label><input id="rollbackOperation"></div><div class="form-group"><label>Tenant ID</label><input id="rollbackTenantId"></div></div><div class="production-exec-actions"><button class="btn btn-outline btn-sm" onclick="previewProductionRollback()">Preview Rollback</button><button class="btn btn-danger btn-sm" onclick="confirmProductionRollback()">Confirm & Rollback</button></div></div>${out()}`;}
  function verification(){const values=engine.snapshot().history;return `${warning()}<div class="report-card">${title('Verification Center')}${values.length?values.map(x=>Object.entries(x.verification.checks).map(([k,v])=>row(`${x.requestId}: ${k}`,v?'Passed':'Failed')).join('')).join(''):row('Status','No verification results')}</div>${out()}`;}
  function content(v){if(v==='execution-queue')return queue(false);if(v==='execution-history')return history();if(v==='pending-operations')return queue(true);if(v==='rollback-manager')return rollback();if(v==='verification-center')return verification();return center();}
  function renderProductionExecutionPage(view){const target=document.getElementById(`production-execution-${view}`);if(target)target.innerHTML=content(view);}function output(v){const target=document.querySelector('.page.active .production-exec-result');if(target)target.textContent=JSON.stringify(v,null,2);}
  async function call(work){try{const v=await work();output(v);return v;}catch(e){output({error:String(e.message||e)});return null;}}
  async function connectProductionExecution(){const session=await sessionProvider();if(!session){output({error:'OWNER_SESSION_REQUIRED'});return null;}return call(async()=>{const value=await engine.connect({edgeFunctionUrl:document.getElementById('productionEdgeUrl').value,anonKey:document.getElementById('productionAnonKey').value},session);renderProductionExecutionPage('execution-center');return value;});}
  async function initializeProductionControlPlane(){if(!ownerSession){output({error:'CONNECT_OWNER_FIRST'});return null;}const expected='INITIALIZE_PRODUCTION_CONTROL',confirmation=root.prompt(`Type exactly: ${expected}`)||'';if(confirmation!==expected){output({cancelled:true,error:'INITIALIZATION_CONFIRMATION_MISMATCH'});return null;}if(!root.confirm('Initialize only the isolated production control schema?'))return null;return call(async()=>{const value=await engine.initializeControlPlane(confirmation);renderProductionExecutionPage('execution-center');return value;});}
  async function toggleProductionMode(enabled){if(!ownerSession){output({error:'CONNECT_OWNER_FIRST'});return null;}const expected=`${enabled?'ENABLE':'DISABLE'}_PRODUCTION:${ownerSession.userId}`,confirmation=root.prompt(`Type exactly: ${expected}`)||'';if(confirmation!==expected){output({cancelled:true,error:'MODE_CONFIRMATION_MISMATCH'});return null;}return call(async()=>{const value=await engine.setMode(enabled,confirmation);renderProductionExecutionPage('execution-center');return value;});}
  let lastPreview=null;function readPayload(){try{return JSON.parse(document.getElementById('productionPayload').value||'{}');}catch{throw new Error('INVALID_PAYLOAD_JSON');}}
  function previewProductionExecution(){const payload={...readPayload(),tenantId:document.getElementById('productionTenantId').value};lastPreview=engine.preview(document.getElementById('productionOperation').value,payload);output(lastPreview);return lastPreview;}
  async function confirmAndExecuteProduction(){if(!lastPreview)previewProductionExecution();const expected=lastPreview.confirmationPhrase,confirmation=root.prompt(`Type exactly: ${expected}`)||'';if(confirmation!==expected){output({cancelled:true,error:'CONFIRMATION_MISMATCH'});return null;}const queued=engine.enqueue(lastPreview,confirmation,ownerSession);if(!queued.valid){output(queued);return queued;}if(!root.confirm(`Execute ${lastPreview.request.operation} now?`))return null;return call(()=>engine.execute(queued.item.requestId));}
  function rollbackValue(){return{executionId:document.getElementById('rollbackExecutionId').value,rollbackId:document.getElementById('rollbackPointId').value,operation:document.getElementById('rollbackOperation').value,tenantId:document.getElementById('rollbackTenantId').value};}
  function previewProductionRollback(){const v=ns.RollbackManager.preview(rollbackValue());output(v);return v;}async function confirmProductionRollback(){const value=rollbackValue(),expected=`ROLLBACK:${value.rollbackId}`,confirmation=root.prompt(`Type exactly: ${expected}`)||'';if(confirmation!==expected){output({cancelled:true,error:'ROLLBACK_CONFIRMATION_MISMATCH'});return null;}if(!root.confirm(`Rollback execution ${value.executionId}?`))return null;return call(()=>engine.rollback(value,confirmation));}
  function previewProductionReport(type){const s=engine.snapshot(),v={type,generatedAt:new Date().toISOString(),mode:s.mode,queue:s.queue,history:s.history,readOnlyPreview:true};output(v);return v;}
  Object.assign(root,{renderProductionExecutionPage,connectProductionExecution,initializeProductionControlPlane,toggleProductionMode,previewProductionExecution,confirmAndExecuteProduction,previewProductionRollback,confirmProductionRollback,previewProductionReport});root.OmniProductionExecutionUi=Object.freeze({version:'1.0.0',engine});
})(typeof globalThis!=='undefined'?globalThis:window);
