import type { GameMeta } from "@sdk/index";
// The single authored roster. `ROSTER.json` is generated by
// online-games/scripts/build-roster.mjs from ROSTER_GATE.safeIds plus each
// game's own meta.ts plus the Arabic strings Ellaz does not ship, and a test
// re-runs the generator in --check mode so this file cannot drift from it.
import roster from "../../../ROSTER.json";

/**
 * The 46 SAFE games, in roster order.
 *
 * ROSTER_IDS comes from ROSTER.json and never from a glob: a glob answers
 * "what directories exist", which is a fact about this checkout, not about
 * what OmniStore is licensed to ship. Ordering is the catalogue's grid order,
 * so it has to survive a file being added to the tree for any other reason.
 */
export const ROSTER_IDS: readonly string[] = roster.games.map((g) => g.id);

/**
 * Metas, keyed by their foundation-relative path, loaded once and statically.
 *
 * `import: "meta"` makes each entry the exported `meta` VALUE, not a module
 * namespace — so it is read directly. Reading `?.meta` off it instead would
 * find nothing and throw at module init, which is the failure this map is
 * designed to surface rather than hide: a browser would report a blank frame.
 */
const META_GLOB = import.meta.glob<GameMeta>("../games/*/meta.ts", {
  eager: true,
  import: "meta",
});

/**
 * Every game's metadata, in roster order.
 *
 * ALL of them, not Ellaz's "above the fold" half. Ellaz splits metadata into
 * `shellRoster` + `gamesRest` because its home grid is one page of prose; this
 * runtime has no home grid — the platform catalog renders from ROSTER.json on
 * its own origin — so the split would buy nothing and cost a second module
 * that has to be kept in step with the first. 46 DOM-free records is a few KB.
 *
 * Undefined is impossible here and the mapping above makes it unrepresentable:
 * a roster id whose meta.ts is missing throws at module init rather than
 * rendering a card with no title.
 */
export const SHELL_GAMES: readonly GameMeta[] = roster.games.map((g) => {
  const meta = META_GLOB[`../games/${g.dir}/meta.ts`];
  if (!meta) {
    throw new Error(`ROSTER.json lists "${g.id}" (dir ${g.dir}) but its meta.ts did not load`);
  }
  if (meta.id !== g.id) {
    throw new Error(`meta.ts in ${g.dir} declares id "${meta.id}", ROSTER.json says "${g.id}"`);
  }
  return meta;
});

/**
 * A control, not decoration: `import.meta.glob` resolves over the DIRECTORY
 * TREE, so if anything ever lands in `runtime/src/games/` that the gate does
 * not sanction, this fails the build instead of quietly adding a 47th entry.
 */
const unexpected = Object.keys(META_GLOB).filter((p) => {
  const dir = p.replace(/^\.\.\/games\//, "").replace(/\/meta\.ts$/, "");
  return !roster.games.some((g) => g.dir === dir);
});
if (unexpected.length > 0) {
  throw new Error(
    "runtime/src/games holds directories ROSTER.json does not sanction: " + unexpected.join(", ")
  );
}
