(function(root){
  'use strict';const ns=root.OmniPlatformAutomation;
  const empty={customers:[],monitoring:{},notifications:{},jobs:[],apiUsage:[],auditLogs:[],deployments:[],subscriptions:[],licenses:[],backups:[],updates:[]};
  const engine=ns.PlatformAutomationEngine.create({provider:{readSnapshot:async()=>empty}});
  const esc=v=>String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const row=(a,b)=>`<div class="self-platform-row"><span>${esc(a)}</span><strong>${esc(typeof b==='object'?JSON.stringify(b):b)}</strong></div>`;
  const notice=()=>'<div class="alert alert-warning"><strong>Self-Managed Platform — Workflow Preview.</strong> لا يوجد اتصال Supabase أو SQL أو نشر أو تعديل بيانات عميل. كل الإجراءات خطط مؤقتة فقط.</div>';
  const out=()=>'<pre class="self-platform-result">No platform workflow has run.</pre>';
  const title=t=>`<div class="table-title">${esc(t)}</div>`;
  const actionLabels={create:'Create Customer',suspend:'Suspend Customer',activate:'Activate Customer',resetPassword:'Reset Password',resetLicense:'Reset License',generateInvite:'Generate Invite',openWorkspace:'Open Workspace',openLogs:'Open Logs',backup:'Backup Customer',restore:'Restore Customer',export:'Export Customer',clone:'Clone Customer',delete:'Delete Customer'};
  function dashboard(){const s=engine.snapshot();return `${notice()}<div class="self-platform-actions"><button class="btn btn-outline btn-sm" onclick="refreshSelfManagedPlatform()">Refresh Read-only Snapshot</button></div><div class="self-platform-grid">${[['Customers',s.customers.length],['Subscriptions',s.subscriptions.length],['Licenses',s.licenses.length],['Deployments',s.deployments.length],['Jobs',s.jobs.length],['Notifications',s.notifications.total],['Workers',s.workers.registered],['Workers Active',s.workers.active]].map(([a,b])=>`<div class="report-card">${row(a,b)}</div>`).join('')}</div>${out()}`;}
  function customers(){const values=engine.snapshot().customers;return `${notice()}<div class="form-grid"><div class="form-group"><label>Search Customers</label><input id="selfCustomerSearch" oninput="filterSelfManagedCustomers()"></div></div><div class="overflow-x"><table class="data-table"><thead><tr><th>Business</th><th>Status</th><th>Plan</th><th>Workspace</th><th>Owner</th><th>Email</th><th>Phone</th><th>Storage</th><th>Database</th><th>Invoices</th><th>Devices</th><th>Last Login</th><th>Last Backup</th></tr></thead><tbody id="selfCustomerRows">${customerRows(values)}</tbody></table></div><div class="report-card" style="margin-top:14px">${title('Customer Actions')}${actionControls()}</div>${out()}`;}
  function customerRows(values){return values.length?values.map(x=>`<tr><td>${esc(x.businessName)}</td><td>${esc(x.status)}</td><td>${esc(x.plan)}</td><td>${esc(x.workspace)}</td><td>${esc(x.owner)}</td><td>${esc(x.email)}</td><td>${esc(x.phone)}</td><td>${x.storage}</td><td>${x.databaseSize}</td><td>${x.invoices}</td><td>${x.activeDevices}</td><td>${esc(x.lastLogin||'—')}</td><td>${esc(x.lastBackup||'—')}</td></tr>`).join(''):'<tr><td colspan="13">No customer snapshot loaded.</td></tr>';}
  function actionControls(){return `<div class="form-grid"><div class="form-group"><label>Tenant ID</label><input id="selfTenantId"></div><div class="form-group"><label>Action</label><select id="selfCustomerAction">${ns.CustomerActionPlanner.ACTIONS.map(x=>`<option value="${x}">${actionLabels[x]}</option>`).join('')}</select></div></div><div class="self-platform-actions"><button class="btn btn-outline btn-sm" onclick="previewSelfCustomerAction()">Preview Customer Action</button></div><div class="alert alert-danger">Delete Customer requires future server confirmation. This phase never deletes customer data.</div>`;}
  function collection(view){const s=engine.snapshot();const map={subscriptions:s.subscriptions,licenses:s.licenses,deployments:s.deployments,updates:s.updates,backups:s.backups,'audit-logs':s.auditLogs,'jobs-queue':s.jobs};const values=map[view]||[];return `${notice()}<div class="report-card">${title(view.replace(/-/g,' ').toUpperCase())}${values.length?values.map((x,i)=>row(`${i+1}`,x)).join(''):row('Status','No snapshot data loaded')}</div>${out()}`;}
  function monitoring(view){const s=engine.snapshot();if(view==='workers')return `${notice()}<div class="report-card">${title('Workers')}${ns.WorkerRegistry.workers.map(x=>row(x.id,`${x.status} — execution disabled`)).join('')}</div>${out()}`;if(view==='notifications')return `${notice()}<div class="report-card">${title('Notifications')}${Object.entries(s.notifications.groups).map(([k,v])=>row(k,v.length)).join('')}${row('Sent','0 — Preview Only')}</div>${out()}`;const signals=s.monitoring.signals||{};return `${notice()}<div class="self-platform-grid">${Object.entries(signals).map(([k,v])=>`<div class="report-card">${title(k)}${row('Status',v.status)}${row('Value',`${v.value} ${v.unit}`)}</div>`).join('')}</div>${out()}`;}
  function usage(view){const u=engine.snapshot().usage;const keys=view==='storage-usage'?['storageBytes']:view==='database-usage'?['databaseBytes']:view==='api-usage'?['apiRequests']:['edgeInvocations'];return `${notice()}<div class="report-card">${title(view.replace(/-/g,' ').toUpperCase())}${keys.map(k=>row(k,u[k])).join('')}</div>${out()}`;}
  function automation(){return `${notice()}<div class="self-platform-grid">${ns.AutomationRegistry.definitions.map(x=>`<div class="report-card">${title(x.name)}${row('Schedule',x.schedule)}${row('Execution','Disabled — Preview')}</div>`).join('')}</div><div class="report-card" style="margin-top:14px">${title('Zero-touch Onboarding Preparation')}<div class="form-grid"><div class="form-group"><label>Business Name</label><input id="zeroBusiness"></div><div class="form-group"><label>Owner Name</label><input id="zeroOwner"></div><div class="form-group"><label>Email</label><input id="zeroEmail"></div><div class="form-group"><label>Business Type</label><input id="zeroType" value="computer_shop"></div></div><div class="self-platform-actions"><button class="btn btn-outline btn-sm" onclick="previewZeroTouchOnboarding()">Prepare Workflow Only</button></div></div>${out()}`;}
  function reports(){return `${notice()}<div class="self-platform-grid">${ns.PlatformReportBuilder.REPORTS.map(type=>`<div class="report-card">${title(`${type} Report`)}<button class="btn btn-outline btn-sm" onclick="previewSelfPlatformReport('${type}')">Preview Report</button></div>`).join('')}</div>${out()}`;}
  function content(view){if(view==='dashboard')return dashboard();if(view==='customers')return customers();if(['subscriptions','licenses','deployments','updates','backups','audit-logs','jobs-queue'].includes(view))return collection(view);if(['monitoring','system-health','notifications','workers'].includes(view))return monitoring(view);if(['storage-usage','database-usage','api-usage','edge-functions'].includes(view))return usage(view);if(view==='automation')return automation();return reports();}
  function renderSelfManagedPlatformPage(view){const target=document.getElementById(`self-platform-${view}`);if(target)target.innerHTML=content(view);}
  function output(v){const target=document.querySelector('.page.active .self-platform-result');if(target)target.textContent=JSON.stringify(v,null,2);}
  async function refreshSelfManagedPlatform(){try{const v=await engine.refresh();renderSelfManagedPlatformPage(document.querySelector('.page.active').id.replace('page-self-platform-',''));output(v);return v;}catch(e){output({error:String(e.message||e)});}}
  function filterSelfManagedCustomers(){const tbody=document.getElementById('selfCustomerRows');if(tbody)tbody.innerHTML=customerRows(engine.searchCustomers(document.getElementById('selfCustomerSearch').value));}
  function previewSelfCustomerAction(){const action=document.getElementById('selfCustomerAction').value,tenantId=document.getElementById('selfTenantId').value;const v=engine.planCustomerAction(action,{tenantId});output(v);return v;}
  function previewZeroTouchOnboarding(){const v=engine.prepareOnboarding({businessName:document.getElementById('zeroBusiness').value,ownerName:document.getElementById('zeroOwner').value,email:document.getElementById('zeroEmail').value,businessType:document.getElementById('zeroType').value});output(v);return v;}
  function previewSelfPlatformReport(type){const v=engine.report(type);output(v);return v;}
  Object.assign(root,{renderSelfManagedPlatformPage,refreshSelfManagedPlatform,filterSelfManagedCustomers,previewSelfCustomerAction,previewZeroTouchOnboarding,previewSelfPlatformReport});root.OmniPlatformAutomationUi=Object.freeze({version:'1.0.0',engine});
})(typeof globalThis!=='undefined'?globalThis:window);
