(function(root){
  'use strict';const ns=root.OmniProductionExecution=root.OmniProductionExecution||{};
  function create(options){options=options||{};const mode=ns.ProductionModeConfiguration.create(),queue=ns.ExecutionQueue.create(),gateway=ns.SecureExecutionGateway.create(options),history=[];const id=()=>typeof options.idFactory==='function'?options.idFactory():root.crypto.randomUUID();
    async function connect(config,session){gateway.configure(config,session);const result=await gateway.invoke('status',{});mode.applyServerStatus({...result.mode,ownerVerified:true});return snapshot();}
    async function initializeControlPlane(confirmation){const result=await gateway.invoke('initialize-control-plane',{confirmation});mode.applyServerStatus({...result.mode,ownerVerified:true});return snapshot();}
    async function setMode(enabled,confirmation){const action=enabled?'enable-mode':'disable-mode';const result=await gateway.invoke(action,{confirmation});mode.applyServerStatus({...result.mode,ownerVerified:true});return snapshot();}
    function preview(operation,payload){const request=ns.ExecutionRequestBuilder.build(operation,payload,id());const estimate=Object.freeze({durationMs:Number(payload&&payload.estimatedDurationMs||0),affectedResources:Number(payload&&payload.affectedResources||0),writesExpected:Boolean(payload&&payload.writesExpected)});return Object.freeze({request,estimate,confirmationPhrase:ns.ConfirmationManager.phrase(request),executed:false});}
    function enqueue(previewValue,confirmation,session){const policy=ns.ExecutionPolicyValidator.validate(previewValue.request.operation,previewValue.request.payload,{mode:mode.snapshot(),session});const confirm=ns.ConfirmationManager.validate(previewValue.request,confirmation);if(!policy.valid||!confirm.valid)return Object.freeze({valid:false,errors:Object.freeze([...policy.errors,...(!confirm.valid?['CONFIRMATION_MISMATCH']:[])])});return Object.freeze({valid:true,item:queue.enqueue({...previewValue.request,confirmation})});}
    async function execute(requestId){const item=queue.get(requestId);if(!item)throw new Error('EXECUTION_REQUEST_NOT_FOUND');queue.replace(requestId,{status:'executing',attempts:item.attempts+1});try{const result=await gateway.invoke('execute',{requestId:item.requestId,operation:item.operation,tenantId:item.tenantId,payload:item.payload,confirmation:item.confirmation});const verification=ns.ExecutionVerifier.validate(result);const audit=ns.ExecutionAuditBuilder.build(result.audit||result);const record=Object.freeze({requestId,item,result,verification,audit,failure:ns.FailureRecoveryEngine.analyze(result),rollback:ns.RollbackManager.preview(result)});history.unshift(record);queue.replace(requestId,{status:verification.valid?'verified':'verification-failed'});return record;}catch(error){queue.replace(requestId,{status:'failed',error:String(error.message||error)});throw error;}}
    async function rollback(execution,confirmation){const plan=ns.RollbackManager.preview(execution);if(!plan.valid)throw new Error(plan.error);return gateway.invoke('rollback',{rollbackId:plan.rollbackId,executionId:plan.executionId,confirmation});}
    function snapshot(){return Object.freeze({mode:mode.snapshot(),gateway:gateway.status(),queue:queue.list(),pending:queue.pending(),history:Object.freeze([...history]),operations:ns.OperationRegistry.definitions});}
    return Object.freeze({connect,initializeControlPlane,setMode,preview,enqueue,execute,rollback,snapshot});
  }
  ns.ProductionExecutionEngine=Object.freeze({version:'1.0.0',create});
})(typeof globalThis!=='undefined'?globalThis:window);
