'use strict';

// ============================================================================
// UPDATE SERVICE (IN-APP UPDATE RAIL)
// ============================================================================
// Serves the update manifest for the client update checker and can launch the
// SEPARATE updater process (bootstrapper) that performs the safe update flow
// (download -> sha256 verify -> backup -> swap -> restart -> health check ->
// rollback). The updater runs detached so it survives the main app exiting.
//
// The manifest file is plain JSON (backend/data/updateManifest.json by
// default) and is generated by scripts/update/generate-manifest.js from a
// release archive. This endpoint NEVER returns secrets — only version
// metadata, the HTTPS download URL, the sha256 digest, and release notes.
// ============================================================================

const fs = require('fs');
const path = require('path');
const { spawn } = require('child_process');
const config = require('../config');
const logger = require('../utils/logger');

// Authoritative application version (single source of truth).
function currentVersion() {
  return config.appVersion || '0.0.0';
}

// Compare two semver-ish versions ("1.2.3"). Returns:
//   -1 if a < b, 0 if equal, 1 if a > b. Non-numeric segments are ignored.
function compareVersions(a, b) {
  const pa = String(a || '0').split('.').map(n => parseInt(n, 10) || 0);
  const pb = String(b || '0').split('.').map(n => parseInt(n, 10) || 0);
  const len = Math.max(pa.length, pb.length);
  for (let i = 0; i < len; i++) {
    const da = pa[i] || 0;
    const db = pb[i] || 0;
    if (da !== db) return da < db ? -1 : 1;
  }
  return 0;
}

// Read + validate the manifest file. Returns a normalized manifest or null.
function readManifest() {
  const file = config.update.manifestPath;
  try {
    if (!fs.existsSync(file)) return null;
    const raw = JSON.parse(fs.readFileSync(file, 'utf-8'));
    if (!raw || typeof raw !== 'object') return null;
    if (!raw.version || typeof raw.version !== 'string') return null;
    return {
      version: String(raw.version),
      releaseDate: typeof raw.releaseDate === 'string' ? raw.releaseDate : '',
      downloadUrl: typeof raw.downloadUrl === 'string' ? raw.downloadUrl : '',
      sha256: typeof raw.sha256 === 'string' ? raw.sha256 : '',
      mandatory: raw.mandatory === true,
      releaseNotes: typeof raw.releaseNotes === 'string' ? raw.releaseNotes : '',
      minimumSupportedVersion: typeof raw.minimumSupportedVersion === 'string' ? raw.minimumSupportedVersion : ''
    };
  } catch (err) {
    logger.warn('update:manifest unreadable:', err.message);
    return null;
  }
}

// Public manifest payload for the client update checker.
function getManifest() {
  const current = currentVersion();
  if (!config.update.enabled) {
    return { updateAvailable: false, currentVersion: current };
  }
  const manifest = readManifest();
  if (!manifest) {
    return { updateAvailable: false, currentVersion: current };
  }
  const newer = compareVersions(manifest.version, current) > 0;
  return {
    updateAvailable: newer,
    currentVersion: current,
    latestVersion: manifest.version,
    releaseDate: manifest.releaseDate,
    downloadUrl: manifest.downloadUrl,
    sha256: manifest.sha256,
    mandatory: manifest.mandatory,
    releaseNotes: manifest.releaseNotes,
    minimumSupportedVersion: manifest.minimumSupportedVersion
  };
}

// Absolute path to the updater bootstrapper for this platform.
function updaterScriptPath() {
  return path.join(__dirname, '..', 'scripts', 'update', 'apply-update.js');
}

// Launch the SEPARATE updater process, detached, so it survives the main app
// exiting. On Windows the .cmd bootstrapper runs minimized in its own console;
// on POSIX the node script is spawned detached with output redirected.
function launchUpdater() {
  if (!config.update.enabled) return { started: false, error: 'updates disabled' };

  const logFile = path.join(config.update.appRoot, 'backups', 'update-run.log');
  try {
    fs.mkdirSync(path.dirname(logFile), { recursive: true });
  } catch (_) {}

  const script = updaterScriptPath();
  if (!fs.existsSync(script)) return { started: false, error: 'updater script missing' };

  const isWin = process.platform === 'win32';
  const updaterCmd = path.join(__dirname, '..', 'scripts', 'update', 'update-bootstrapper.cmd');

  try {
    if (isWin) {
      // Detached, minimized console — the updater keeps running after this
      // process exits (it must, to stop/restart the service).
      // NOTE: pass the path WITHOUT manual quotes. Node's spawn quotes
      // arguments containing spaces itself; pre-quoting made cmd receive
      // \"...\" and the bootstrapper never launched.
      spawn('cmd.exe', ['/c', 'start', '', '/min', updaterCmd], {
        detached: true,
        stdio: 'ignore',
        windowsHide: true
      }).unref();
    } else {
      const out = fs.openSync(logFile, 'a');
      const child = spawn(process.execPath, [script], {
        detached: true,
        stdio: ['ignore', out, out]
      });
      child.unref();
      try { fs.closeSync(out); } catch (_) {}
    }
    logger.info('update:updater launched');
    return { started: true, logFile };
  } catch (err) {
    logger.error('update:launch failed:', err.message);
    return { started: false, error: err.message };
  }
}

module.exports = {
  currentVersion,
  compareVersions,
  getManifest,
  readManifest,
  launchUpdater,
  updaterScriptPath
};
