(function(root){
  'use strict';const ns=root.OmniRecoveryPlatform;const engine=ns.RecoveryPlatformEngine.create({provider:{readSnapshot:async()=>({snapshots:[],versions:{},health:{},rollbackHistory:[]})}});
  const esc=v=>String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const row=(a,b)=>`<div class="recovery-platform-row"><span>${esc(a)}</span><strong>${esc(typeof b==='object'?JSON.stringify(b):b)}</strong></div>`;const title=x=>`<div class="table-title">${esc(x)}</div>`;
  const notice=()=>'<div class="alert alert-warning"><strong>Recovery Platform — Preview Only.</strong> لا يتم إنشاء Backup أو Restore أو Update أو Rollback، ولا توجد كتابة ملفات أو SQL أو Supabase.</div>';const out=()=>'<pre class="recovery-platform-result">No recovery preview has run.</pre>';
  function center(){const s=engine.snapshot();return `${notice()}<div class="recovery-platform-actions"><button class="btn btn-outline btn-sm" onclick="refreshRecoveryPlatform()">Refresh Recovery Snapshot</button></div><div class="recovery-platform-grid"><div class="report-card">${title('Recovery Health')}${row('Score',s.health?`${s.health.score}%`:'Not loaded')}</div><div class="report-card">${title('Snapshots')}${row('Count',s.snapshots.length)}</div><div class="report-card">${title('Current Version')}${row('Version',s.versions.currentVersion)}</div><div class="report-card">${title('Rollback History')}${row('Count',s.rollbackHistory.length)}</div></div><div class="report-card" style="margin-top:14px">${title('Reports')}${ns.RecoveryReportBuilder.TYPES.map(t=>`<button class="btn btn-outline btn-sm" style="margin:4px" onclick="previewRecoveryReport('${t}')">${esc(t)} Report</button>`).join('')}</div>${out()}`;}
  function backups(){return `${notice()}<div class="report-card">${title('Backup Preview Engine')}<div class="form-grid"><div class="form-group"><label>Tenant ID</label><input id="recoveryTenantId"></div><div class="form-group"><label>Backup Type</label><select id="recoveryBackupType">${ns.BackupPreviewEngine.TYPES.map(t=>`<option value="${t}">${t}</option>`).join('')}</select></div><div class="form-group"><label>Estimated Bytes</label><input id="recoveryBackupBytes" type="number" min="0" value="0"></div></div><div class="recovery-platform-actions"><button class="btn btn-outline btn-sm" onclick="previewRecoveryBackup()">Preview Backup — No Execution</button></div></div>${out()}`;}
  function restore(){return `${notice()}<div class="report-card">${title('Restore Wizard')}<div class="form-grid"><div class="form-group"><label>Backup ID</label><input id="restoreBackupId"></div><div class="form-group"><label>Tenant ID</label><input id="restoreTenantId"></div><div class="form-group"><label>Backup Version</label><input id="restoreBackupVersion" value="1.0.0"></div><div class="form-group"><label>Current Version</label><input id="restoreCurrentVersion" value="1.0.0"></div><div class="form-group"><label>Storage Bytes</label><input id="restoreStorageBytes" type="number" value="0"></div><div class="form-group"><label>Available Bytes</label><input id="restoreAvailableBytes" type="number" value="1000000"></div></div><div class="recovery-platform-actions"><button class="btn btn-outline btn-sm" onclick="previewRecoveryRestore()">Restore Preview</button></div>${row('Compare Backup','Enabled')}${row('Conflict Detection','Enabled')}${row('Missing Files Detection','Enabled')}${row('Overwrite','Preview only')}${row('Validation and Estimate','Enabled')}</div>${out()}`;}
  function snapshots(){const values=engine.browseSnapshots({});return `${notice()}<div class="overflow-x"><table class="data-table"><thead><tr><th>ID</th><th>Tenant</th><th>Type</th><th>Created</th><th>Size</th><th>Status</th><th>Checksum</th></tr></thead><tbody>${values.length?values.map(x=>`<tr><td>${esc(x.id)}</td><td>${esc(x.tenantId)}</td><td>${esc(x.type)}</td><td>${esc(x.createdAt)}</td><td>${x.size}</td><td>${esc(x.status)}</td><td>${esc(x.checksum)}</td></tr>`).join(''):'<tr><td colspan="7">No snapshot metadata loaded.</td></tr>'}</tbody></table></div>${out()}`;}
  function update(){return `${notice()}<div class="report-card">${title('Update Center')}<div class="form-grid"><div class="form-group"><label>Installed Version</label><input id="recoveryInstalledVersion" value="1.0.0"></div><div class="form-group"><label>Latest Version</label><input id="recoveryLatestVersion" value="1.1.0"></div><div class="form-group"><label>Rollback Target</label><input id="recoveryRollbackTarget" value="1.0.0"></div></div><div class="recovery-platform-actions"><button class="btn btn-outline btn-sm" onclick="previewRecoveryUpdate()">Check Updates — Preview</button></div>${row('Release Notes','Preview')}${row('Compatibility Check','Required')}${row('Required Migration','Preview only')}${row('Backup Required','Calculated')}${row('Rollback Availability','Calculated')}</div>${out()}`;}
  function versions(){const v=engine.snapshot().versions;return `${notice()}<div class="recovery-platform-grid"><div class="report-card">${title('Current Version')}${row('Version',v.currentVersion)}</div><div class="report-card">${title('Previous Versions')}${row('Versions',v.previousVersions)}</div><div class="report-card">${title('Installed Builds')}${row('Builds',v.installedBuilds.length)}</div><div class="report-card">${title('Rollback Targets')}${row('Targets',v.rollbackTargets)}</div><div class="report-card">${title('Upgrade History')}${row('Entries',v.upgradeHistory.length)}</div></div>${out()}`;}
  function history(){const values=engine.snapshot().rollbackHistory;return `${notice()}<div class="report-card">${title('Rollback History')}${values.length?values.map((x,i)=>row(`${i+1}`,x)).join(''):row('Status','No history loaded')}</div>${out()}`;}
  function health(){const h=engine.snapshot().health;return `${notice()}<div class="report-card">${title('Recovery Health')}${h?row('Backup Age',h.backupAgeDays)+row('Storage Usage',`${h.storageUsage}%`)+Object.entries(h.checks).map(([k,v])=>row(k,v?'Passed':'Review')).join('')+row('Score',`${h.score}%`):row('Status','Not loaded')}</div>${out()}`;}
  function audit(){const values=engine.snapshot().audit;return `${notice()}<div class="report-card">${title('Recovery Audit')}${values.length?values.map(x=>row(x.type,x.createdAt)).join(''):row('Status','No preview events in this session')}</div>${out()}`;}
  function content(v){if(v==='backups')return backups();if(v==='restore-wizard')return restore();if(v==='snapshot-browser')return snapshots();if(v==='update-center')return update();if(v==='installed-versions')return versions();if(v==='rollback-history')return history();if(v==='recovery-health')return health();if(v==='recovery-audit')return audit();return center();}
  function renderRecoveryPlatformPage(view){const target=document.getElementById(`recovery-platform-${view}`);if(target)target.innerHTML=content(view);}function output(v){const target=document.querySelector('.page.active .recovery-platform-result');if(target)target.textContent=JSON.stringify(v,null,2);}
  async function refreshRecoveryPlatform(){try{const v=await engine.refresh();renderRecoveryPlatformPage(document.querySelector('.page.active').id.replace('page-recovery-platform-',''));output(v);return v;}catch(e){output({error:String(e.message||e)});}}
  function previewRecoveryBackup(){const v=engine.backupPreview(document.getElementById('recoveryBackupType').value,{tenantId:document.getElementById('recoveryTenantId').value,estimatedBytes:Number(document.getElementById('recoveryBackupBytes').value)});output(v);return v;}
  function previewRecoveryRestore(){const id=document.getElementById('restoreBackupId').value,tenantId=document.getElementById('restoreTenantId').value;const backup={id,tenantId,checksum:'preview-checksum',manifest:true,createdAt:new Date().toISOString(),status:'verified',version:document.getElementById('restoreBackupVersion').value,storageBytes:Number(document.getElementById('restoreStorageBytes').value),files:[]};const current={tenantId,version:document.getElementById('restoreCurrentVersion').value,availableBytes:Number(document.getElementById('restoreAvailableBytes').value),files:[]};const v=engine.restorePreview(backup,current,{overwrite:true});output(v);return v;}
  function previewRecoveryUpdate(){const v=engine.updatePreview({installedVersion:document.getElementById('recoveryInstalledVersion').value,latestVersion:document.getElementById('recoveryLatestVersion').value,rollbackTarget:document.getElementById('recoveryRollbackTarget').value,compatible:true,releaseNotes:[],requiredMigrations:[]});output(v);return v;}
  function previewRecoveryReport(type){const v=engine.report(type);output(v);return v;}
  Object.assign(root,{renderRecoveryPlatformPage,refreshRecoveryPlatform,previewRecoveryBackup,previewRecoveryRestore,previewRecoveryUpdate,previewRecoveryReport});root.OmniRecoveryPlatformUi=Object.freeze({version:'1.0.0',engine});
})(typeof globalThis!=='undefined'?globalThis:window);
