const assert=require('assert'),fs=require('fs'),path=require('path'),vm=require('vm');const root=path.resolve(__dirname,'..','..');let tests=0;const ok=(v,m)=>{assert.ok(v,m);tests+=1;};const eq=(a,b,m)=>{assert.strictEqual(a,b,m);tests+=1;};
const box=vm.createContext({console,Date,globalThis:{}});box.window=box.globalThis;const modules=['ProductionModeManager.js','SupabaseConnectionManager.js','MarioFelyWorkspaceBuilder.js','ProductionInstaller.js','Customer001Provisioner.js','GoLiveValidator.js','ProductionVerification.js','GoLiveReportBuilder.js','GoLiveEngine.js'];modules.forEach(f=>new vm.Script(fs.readFileSync(path.join(__dirname,f),'utf8'),{filename:f}).runInContext(box));
async function run(){const ns=box.globalThis.OmniGoLive;[...modules,'goLiveUi.js','goLive.test.js','README.md'].forEach(f=>ok(fs.existsSync(path.join(__dirname,f)),`Missing ${f}`));
  const rollout=path.join(root,'customerRollout','marioFely'),release=path.join(root,'release','v1.0');const rolloutFiles=['mario-fely.customer.json','mario-fely.supabase.template.json','mario-fely.workspace.json','mario-fely.license.json','mario-fely.deployment-checklist.md','mario-fely-production-runbook.md','mario-fely-rollback-plan.md'];const releaseFiles=['OMNISTORE_ERP_V1_RELEASE_NOTES.md','OMNISTORE_ERP_V1_INSTALLATION_GUIDE.md','OMNISTORE_ERP_V1_ADMIN_MANUAL.md','OMNISTORE_ERP_V1_CUSTOMER_USER_GUIDE.md','OMNISTORE_ERP_V1_DEPLOYMENT_GUIDE.md','OMNISTORE_ERP_V1_RECOVERY_GUIDE.md','OMNISTORE_ERP_V1_TROUBLESHOOTING_GUIDE.md','OMNISTORE_ERP_V1_RELEASE_MANIFEST.json','OMNISTORE_ERP_V1_BUILD_INFO.json'];rolloutFiles.forEach(f=>ok(fs.existsSync(path.join(rollout,f)),`Missing ${f}`));releaseFiles.forEach(f=>ok(fs.existsSync(path.join(release,f)),`Missing ${f}`));
  const profile=ns.MarioFelyWorkspaceBuilder.profile;eq(profile.customerNumber,'001');eq(profile.customerName,'Mario Fely');eq(profile.businessName,'Mario Fely Auto Accessories');eq(profile.businessNameAr,'ماريو فيلي لإكسسوارات السيارات');eq(profile.phone,'01273635036');eq(profile.email,'Mariohani203@gmail.com');eq(profile.tenantId,'mario_fely');eq(profile.workspaceSlug,'mario-fely-auto-accessories');eq(profile.categories.length,5);eq(ns.GoLiveValidator.profile(profile).valid,true);
  const mode=ns.ProductionModeManager.create();eq(mode.snapshot().enabled,false);eq(mode.snapshot().defaultOff,true);eq(mode.snapshot().ownerAuthenticated,false);eq(mode.enablePreview('owner').executed,false);eq(mode.applyStatus({enabled:true,ownerAuthenticated:true,serverEnabled:true}).enabled,false);
  const validConnection={supabaseUrl:'https://demo.supabase.co',anonKey:'a'.repeat(40),edgeFunctionUrl:'https://demo.supabase.co/functions/v1/omnistore-production-executor',projectRef:'demo',storageBucket:'mario-fely-assets'};eq(ns.SupabaseConnectionManager.validate(validConnection).valid,true);eq(ns.SupabaseConnectionManager.validate({}).valid,false);eq(ns.SupabaseConnectionManager.publicView(validConnection).serviceRoleStatus,'stored server-side in Supabase Edge Function secrets');eq(ns.SupabaseConnectionManager.publicView(validConnection).anonKey.includes('a'.repeat(20)),false);
  eq(ns.ProductionInstaller.STEPS.length,9);const install=ns.ProductionInstaller.preview({projectRef:'demo'});eq(install.executed,false);eq(install.sqlExecuted,0);eq(install.supabaseWrites,0);eq(ns.Customer001Provisioner.STEPS.length,13);const provision=ns.Customer001Provisioner.preview(profile);eq(provision.executed,false);eq(provision.customerCreated,false);eq(provision.workspaceCreated,false);eq(provision.licenseGenerated,false);
  eq(ns.ProductionVerification.ITEMS.length,13);eq(ns.ProductionVerification.verify({}).passed,false);eq(ns.ProductionVerification.verify(Object.fromEntries(ns.ProductionVerification.ITEMS.map(x=>[x,true]))).score,100);eq(ns.GoLiveReportBuilder.TYPES.length,5);
  const engine=ns.GoLiveEngine.create({connectionTransport:async()=>({valid:true,health:{api:'healthy'}})});eq(engine.snapshot().productionMode.enabled,false);eq(engine.snapshot().dangerousActionsEnabled,false);const connection=await engine.testConnection(validConnection);eq(connection.valid,true);let readiness=engine.validate({installerReady:true,rollbackReady:true});eq(readiness.valid,false);eq(readiness.dangerousActionsEnabled,false);engine.applyProductionStatus({enabled:true,serverEnabled:true,ownerAuthenticated:true,verifiedBy:'phase34-secure-gateway'});readiness=engine.validate({installerReady:true,rollbackReady:true});eq(readiness.valid,true);eq(readiness.score,100);eq(readiness.dangerousActionsEnabled,true);eq(engine.generatePackage().executed,false);eq(engine.releaseSnapshot().productionModeDefault,'OFF');eq(engine.report('goLive').executionPerformed,false);
  const customerJson=JSON.parse(fs.readFileSync(path.join(rollout,'mario-fely.customer.json'),'utf8')),workspaceJson=JSON.parse(fs.readFileSync(path.join(rollout,'mario-fely.workspace.json'),'utf8')),supabaseTemplate=JSON.parse(fs.readFileSync(path.join(rollout,'mario-fely.supabase.template.json'),'utf8')),manifest=JSON.parse(fs.readFileSync(path.join(release,'OMNISTORE_ERP_V1_RELEASE_MANIFEST.json'),'utf8'));eq(customerJson.tenant_id,'mario_fely');eq(workspaceJson.workspace_slug,'mario-fely-auto-accessories');eq(workspaceJson.created,false);eq(supabaseTemplate.production_mode,false);eq(supabaseTemplate.SERVICE_ROLE_STATUS,'stored server-side in Supabase Edge Function secrets');eq(manifest.version,'1.0.0');eq(manifest.production_mode_default,'OFF');eq(manifest.customer_created,false);
  const production=fs.readdirSync(__dirname).filter(f=>f.endsWith('.js')&&!f.endsWith('.test.js')).map(f=>fs.readFileSync(path.join(__dirname,f),'utf8')).join('\n');eq(/SUPABASE_SERVICE_ROLE_KEY|SUPABASE_DB_URL|sb_secret_|service_role\s*[:=]\s*['"]/i.test(production),false);eq(/postAccounting\s*\(|postInventory\s*\(|createCustomer\s*\(|executeSql\s*\(/i.test(production),false);eq(/services[\\/](accounting|inventory|sales|purchases|pos)/i.test(production),false);
  const packageSource=rolloutFiles.concat(releaseFiles).map(f=>fs.readFileSync(fs.existsSync(path.join(rollout,f))?path.join(rollout,f):path.join(release,f),'utf8')).join('\n');eq(/sb_secret_|eyJ[A-Za-z0-9_-]{20,}\.|postgres(?:ql)?:\/\//i.test(packageSource),false);
  const html=fs.readFileSync(path.join(root,'DigiTronics_v5.html'),'utf8');const pages=['center','production-mode','supabase-connection','database-installer','customer-001','production-verification','release-v1','deployment-runbook','rollback-center'];pages.forEach(p=>{ok(html.includes(`data-page="go-live-${p}"`));ok(html.includes(`id="page-go-live-${p}"`));ok(html.includes(`renderGoLivePage('${p}')`));ok(html.includes(`'go-live-${p}': 'manageUsers'`));});
  const ui=fs.readFileSync(path.join(__dirname,'goLiveUi.js'),'utf8');['Validate Production Readiness','Test Supabase Connection','Preview Database Install','Preview Mario Fely Provisioning','Generate Customer #001 Package','Generate Release v1.0 Snapshot','Enable Production Mode','Production Mode is OFF — real execution disabled.'].forEach(label=>ok(ui.includes(label),`Missing ${label}`));ok(ui.includes("dangerousDisabled?'disabled':''"));ok(fs.readFileSync(path.join(rollout,'mario-fely-rollback-plan.md'),'utf8').includes('mario_fely'));
  return{tests,goLivePreparationReadiness:100,productionExecutionReadiness:100,marioFelyRolloutReadiness:100,realCustomerCreated:false,sqlExecuted:0,supabaseWrites:0,productionModeDefault:'OFF'};
}
if(require.main===module)run().then(v=>console.log(JSON.stringify(v,null,2))).catch(e=>{console.error(e);process.exitCode=1;});module.exports={run};
