(function(root){
  'use strict';const ns=root.OmniGoLive;
  async function connectionTransport(config){const client=typeof root.getSupabaseClient==='function'?root.getSupabaseClient():null;const sessionResult=client&&client.auth?await client.auth.getSession():null;const token=sessionResult&&sessionResult.data&&sessionResult.data.session&&sessionResult.data.session.access_token;if(!token)return{valid:false,health:{error:'OWNER_SESSION_REQUIRED'}};const response=await root.fetch(config.edgeFunctionUrl,{method:'POST',headers:{apikey:config.anonKey,Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({action:'status'})});const body=await response.json().catch(()=>({}));return{valid:response.ok,health:body};}
  const engine=ns.GoLiveEngine.create({connectionTransport});const esc=v=>String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const row=(a,b)=>`<div class="go-live-row"><span>${esc(a)}</span><strong>${esc(typeof b==='object'?JSON.stringify(b):b)}</strong></div>`;const title=x=>`<div class="table-title">${esc(x)}</div>`;
  const warning=()=>'<div class="alert alert-danger"><strong>Production Mode is OFF — real execution disabled.</strong><br>التجهيز الحالي لا ينشئ عميلًا أو قاعدة بيانات. التنفيذ لاحقًا يتطلب Phase 34 وERP Owner واتصالًا صالحًا وتأكيدًا وRollback Point.</div>';const out=()=>'<pre class="go-live-result">No Go Live action has run.</pre>';
  function customerCard(){const p=engine.snapshot().profile;return `<div class="report-card">${title('Customer #001 — Mario Fely')}${row('Business',p.businessName)}${row('النشاط',p.businessNameAr)}${row('Phone',p.phone)}${row('Email',p.email)}${row('Address',p.addressAr)}${row('Activity',p.activity)}${row('Tenant ID',p.tenantId)}${row('Workspace',p.workspaceSlug)}${row('Categories',p.categories)}</div>`;}
  function center(){const s=engine.snapshot(),dangerousDisabled=!s.productionMode.enabled||!s.readiness.valid;return `${warning()}<div class="go-live-actions"><button class="btn btn-outline btn-sm" onclick="validateGoLiveReadiness()">Validate Production Readiness</button><button class="btn btn-outline btn-sm" onclick="previewGoLiveInstaller()">Preview Database Install</button><button class="btn btn-outline btn-sm" onclick="previewMarioFelyProvisioning()">Preview Mario Fely Provisioning</button><button class="btn btn-outline btn-sm" onclick="generateMarioFelyPackage()">Generate Customer #001 Package</button><button class="btn btn-outline btn-sm" onclick="generateV1ReleaseSnapshot()">Generate Release v1.0 Snapshot</button><button class="btn btn-danger btn-sm" onclick="previewEnableProductionMode()" ${dangerousDisabled?'disabled':''}>Enable Production Mode</button></div><div class="go-live-grid">${customerCard()}<div class="report-card">${title('Go Live Readiness')}${row('Score',`${s.readiness.score}%`)}${row('Validation',s.readiness.valid?'Passed':'Blocked')}${row('Dangerous Actions',s.dangerousActionsEnabled?'Enabled':'Disabled')}${row('Production Mode','OFF by default')}${row('Customer Created','No')}</div></div>${out()}`;}
  function production(){const s=engine.snapshot();return `${warning()}<div class="report-card">${title('Production Mode')}${row('Enabled',s.productionMode.enabled)}${row('Server Enabled',s.productionMode.serverEnabled)}${row('Owner Authenticated',s.productionMode.ownerAuthenticated)}${row('Default OFF',s.productionMode.defaultOff)}<div class="go-live-actions"><button class="btn btn-outline btn-sm" onclick="previewEnableProductionMode()">Prepare Phase 34 Enable Request</button></div></div>${out()}`;}
  function connection(){return `${warning()}<div class="report-card">${title('Production Supabase Connection Setup')}<div class="form-grid"><div class="form-group"><label>SUPABASE_URL</label><input id="goLiveSupabaseUrl" autocomplete="off"></div><div class="form-group"><label>SUPABASE_ANON_KEY</label><input id="goLiveAnonKey" type="password" autocomplete="off"></div><div class="form-group"><label>EDGE_FUNCTION_URL</label><input id="goLiveEdgeUrl" autocomplete="off"></div><div class="form-group"><label>PROJECT_REF</label><input id="goLiveProjectRef" autocomplete="off"></div><div class="form-group"><label>STORAGE_BUCKET</label><input id="goLiveBucket" value="mario-fely-assets"></div><div class="form-group"><label>JWT_SECRET_STATUS</label><input id="goLiveJwtStatus" value="stored server-side" readonly></div><div class="form-group"><label>SERVICE_ROLE_STATUS</label><input value="stored server-side in Supabase Edge Function secrets" readonly></div></div><button class="btn btn-outline btn-sm" onclick="testGoLiveSupabaseConnection()">Test Supabase Connection</button><div class="alert alert-info" style="margin-top:12px">Create the Supabase project, add Edge Function secrets server-side, test connection, preview database install, then preview workspace provisioning.</div></div>${out()}`;}
  function installer(){const v=engine.installerPreview();return `${warning()}<div class="report-card">${title('Database Installer Workflow')}${v.steps.map(x=>row(`${x.order}. ${x.id}`,x.status)).join('')}${row('SQL Executed',v.sqlExecuted)}${row('Supabase Writes',v.supabaseWrites)}</div>${out()}`;}
  function customer(){return `${warning()}${customerCard()}<div class="report-card" style="margin-top:14px">${title('Mario Fely Provisioning Workflow')}${engine.provisioningPreview().steps.map(x=>row(`${x.order}. ${x.id}`,x.status)).join('')}</div>${out()}`;}
  function verification(){const result=ns.ProductionVerification.verify({});return `${warning()}<div class="report-card">${title('Production Verification Checklist')}${Object.entries(result.checks).map(([k,v])=>row(k,v?'Passed':'Pending')).join('')}${row('Current Score',`${result.score}%`)}</div>${out()}`;}
  function release(){const v=engine.releaseSnapshot();return `${warning()}<div class="report-card">${title('OmniStore ERP v1.0 Commercial Release')}${Object.entries(v).map(([k,x])=>row(k,x)).join('')}</div>${out()}`;}
  function runbook(){return `${warning()}<div class="report-card">${title('Deployment Runbook')}${['Create Supabase project','Add Edge Function secrets','Test connection','Preview database install','Create rollback point','Enable Phase 34 Production Mode','Execute one operation','Verify workspace','Disable Production Mode'].map((x,i)=>row(`${i+1}`,x)).join('')}</div>${out()}`;}
  function rollback(){return `${warning()}<div class="report-card">${title('Rollback Center')}${['Stop subsequent operations','Verify tenant mario_fely','Select operation rollback point','Use Phase 34 Rollback Manager','Verify all workspace components','Preserve audit','Disable Production Mode'].map((x,i)=>row(`${i+1}`,x)).join('')}</div>${out()}`;}
  function content(v){if(v==='production-mode')return production();if(v==='supabase-connection')return connection();if(v==='database-installer')return installer();if(v==='customer-001')return customer();if(v==='production-verification')return verification();if(v==='release-v1')return release();if(v==='deployment-runbook')return runbook();if(v==='rollback-center')return rollback();return center();}
  function renderGoLivePage(view){const target=document.getElementById(`go-live-${view}`);if(target)target.innerHTML=content(view);}function output(v){const target=document.querySelector('.page.active .go-live-result');if(target)target.textContent=JSON.stringify(v,null,2);}async function call(work){try{const v=await work();output(v);return v;}catch(e){output({error:String(e.message||e)});return null;}}
  function connectionInput(){return{supabaseUrl:document.getElementById('goLiveSupabaseUrl').value,anonKey:document.getElementById('goLiveAnonKey').value,edgeFunctionUrl:document.getElementById('goLiveEdgeUrl').value,projectRef:document.getElementById('goLiveProjectRef').value,storageBucket:document.getElementById('goLiveBucket').value,jwtSecretStatus:document.getElementById('goLiveJwtStatus').value};}
  async function testGoLiveSupabaseConnection(){return call(()=>engine.testConnection(connectionInput()));}function validateGoLiveReadiness(){const v=engine.validate({installerReady:true,rollbackReady:true});renderGoLivePage('center');output(v);return v;}function previewGoLiveInstaller(){const v=engine.installerPreview();output(v);return v;}function previewMarioFelyProvisioning(){const v=engine.provisioningPreview();output(v);return v;}function generateMarioFelyPackage(){const v=engine.generatePackage();output(v);return v;}function generateV1ReleaseSnapshot(){const v=engine.releaseSnapshot();output(v);return v;}function previewEnableProductionMode(){const v=engine.enableProductionPreview('authenticated-owner-required');output(v);return v;}
  Object.assign(root,{renderGoLivePage,testGoLiveSupabaseConnection,validateGoLiveReadiness,previewGoLiveInstaller,previewMarioFelyProvisioning,generateMarioFelyPackage,generateV1ReleaseSnapshot,previewEnableProductionMode});root.OmniGoLiveUi=Object.freeze({version:'1.0.0',engine});
})(typeof globalThis!=='undefined'?globalThis:window);
