(function(root){
  'use strict';const ns=root.OmniPlatformAutomation=root.OmniPlatformAutomation||{};
  function create(options){options=options||{};let state={customers:Object.freeze([]),monitoring:ns.SystemMonitoringAggregator.aggregate(),notifications:ns.PlatformNotificationAggregator.aggregate(),jobs:Object.freeze([]),usage:ns.UsageAnalytics.build(),auditLogs:Object.freeze([]),deployments:Object.freeze([]),subscriptions:Object.freeze([]),licenses:Object.freeze([]),backups:Object.freeze([]),updates:Object.freeze([])};
    const snapshot=()=>Object.freeze({...state,workers:ns.WorkerRegistry.health(),automations:ns.AutomationSchedulerPreview.build(ns.AutomationRegistry.definitions),readOnly:true});
    async function refresh(){if(!options.provider||typeof options.provider.readSnapshot!=='function')throw new Error('READ_ONLY_PLATFORM_PROVIDER_REQUIRED');const raw=await options.provider.readSnapshot();const check=ns.PlatformAutomationValidator.validate(raw);if(!check.valid)return check;state={customers:Object.freeze((raw.customers||[]).map(ns.CustomerDirectory.normalize)),monitoring:ns.SystemMonitoringAggregator.aggregate(raw.monitoring),notifications:ns.PlatformNotificationAggregator.aggregate(raw.notifications),jobs:ns.JobsQueuePreview.normalize(raw.jobs),usage:ns.UsageAnalytics.build(raw.customers,raw.apiUsage),auditLogs:Object.freeze(raw.auditLogs||[]),deployments:Object.freeze(raw.deployments||[]),subscriptions:Object.freeze(raw.subscriptions||[]),licenses:Object.freeze(raw.licenses||[]),backups:Object.freeze(raw.backups||[]),updates:Object.freeze(raw.updates||[])};return snapshot();}
    return Object.freeze({refresh,snapshot,searchCustomers:q=>ns.CustomerDirectory.search(state.customers,q),planCustomerAction:ns.CustomerActionPlanner.plan,confirmDelete:ns.CustomerActionPlanner.confirm,prepareOnboarding:ns.ZeroTouchOnboardingWorkflow.prepare,report:type=>ns.PlatformReportBuilder.build(type,snapshot())});
  }
  ns.PlatformAutomationEngine=Object.freeze({version:'1.0.0',create});
})(typeof globalThis!=='undefined'?globalThis:window);
