const assert=require('assert'),fs=require('fs'),path=require('path'),vm=require('vm');const root=path.resolve(__dirname,'..','..');let tests=0;const ok=(v,m)=>{assert.ok(v,m);tests+=1;};const eq=(a,b,m)=>{assert.strictEqual(a,b,m);tests+=1;};
const box=vm.createContext({console,Date,RegExp,globalThis:{}});box.window=box.globalThis;const modules=['IntentRegistry.js','SmartSearchEngine.js','SalesInsightEngine.js','InventoryInsightEngine.js','AccountingInsightEngine.js','PurchaseInsightEngine.js','CustomerSupplierInsightEngine.js','KnowledgeCenter.js','TrainingAssistant.js','AIReportBuilder.js','CopilotSecurityValidator.js','BusinessCopilotEngine.js'];modules.forEach(f=>new vm.Script(fs.readFileSync(path.join(__dirname,f),'utf8'),{filename:f}).runInContext(box));
async function run(){const ns=box.globalThis.OmniAICopilot;[...modules,'aiCopilotUi.js','aiCopilot.test.js','README.md'].forEach(f=>ok(fs.existsSync(path.join(__dirname,f)),`Missing ${f}`));
  eq(ns.IntentRegistry.intents.length,10);const intentCases={low_stock:['Products below minimum stock','Low stock items','مخزون منخفض'],today_sales:["Today's sales",'مبيعات اليوم'],awaiting_payment:['Invoices awaiting payment','فواتير غير مدفوعة'],best_sellers:['Best selling products','أفضل المنتجات'],inactive_customers:['Inactive customers','عملاء غير نشطين'],monthly_profit:['Profit this month','أرباح الشهر'],top_supplier:['Most purchased supplier','أفضل مورد'],dead_stock:['Dead stock','مخزون راكد'],fast_moving:['Fast moving items'],help:['How to use reports','مساعدة']};Object.entries(intentCases).forEach(([intent,queries])=>queries.forEach(q=>eq(ns.IntentRegistry.detect(q).id,intent,`${q}`)));
  const data={products:[{id:'p1',name:'Low',stock:1,minStock:2,soldQty:0,dailyDemand:1},{id:'p2',name:'Fast',stock:10,minStock:2,soldQty:20,dailyDemand:2}],sales:[{id:'s1',date:'2026-07-02',total:100,cost:60},{id:'s2',date:'2026-06-01',total:50,cost:30}],invoices:[{id:'i1',paymentStatus:'pending',due:10},{id:'i2',paymentStatus:'paid',due:0}],customers:[{id:'c1',lastActivity:'2025-01-01',totalSpent:100},{id:'c2',lastActivity:'2026-07-01',totalSpent:50}],suppliers:[{id:'sup1'}],purchases:[{supplierId:'sup1',total:200}],expenses:[{date:'2026-07-02',amount:10,category:'rent'}]};
  const searchCases=[['Products below minimum stock',1],["Today's sales",1],['Sales today',1],['Invoices awaiting payment',1],['Best selling products',2],['Inactive customers',1],['Profit this month',1],['Most purchased supplier',1],['Dead stock',1]];searchCases.forEach(([q,count])=>eq(ns.SmartSearchEngine.search(q,data,'2026-07-02').count,count,q));eq(ns.SmartSearchEngine.search('unknown query',data,'2026-07-02').actionsExecuted,0);
  const sales=ns.SalesInsightEngine.analyze(data);eq(sales.totalSales,150);eq(sales.grossProfit,60);eq(sales.readOnly,true);const inventory=ns.InventoryInsightEngine.analyze(data);eq(inventory.lowStock.length,1);eq(inventory.deadStock.length,1);eq(inventory.fastMoving[0].id,'p2');eq(inventory.writes,0);const accounting=ns.AccountingInsightEngine.analyze(data);eq(accounting.revenue,150);eq(accounting.netProfit,50);eq(accounting.officialStatement,false);eq(accounting.postingPerformed,false);const purchase=ns.PurchaseInsightEngine.analyze(data);eq(purchase.recommendations.length,1);eq(purchase.ordersCreated,0);eq(ns.CustomerSupplierInsightEngine.customers(data).inactive.length,1);eq(ns.CustomerSupplierInsightEngine.suppliers(data).ranking[0].supplierId,'sup1');
  eq(ns.KnowledgeCenter.articles.length,6);eq(ns.KnowledgeCenter.answer('Explain reports').id,'reports');eq(ns.TrainingAssistant.topics.length,8);eq(ns.TrainingAssistant.lesson('inventory').actionsExecuted,0);eq(ns.AIReportBuilder.TYPES.length,4);ns.AIReportBuilder.TYPES.forEach(type=>eq(ns.AIReportBuilder.build(type,{}).valid,true));
  eq(ns.CopilotSecurityValidator.validate('show low stock').safe,true);['execute sale','delete customer','update invoice','post journal','save changes','deploy now','restore backup','activate license','suspend customer'].forEach(q=>eq(ns.CopilotSecurityValidator.validate(q).safe,false,q));
  const provider={readSnapshot:async()=>data},engine=ns.BusinessCopilotEngine.create({provider,now:()=> '2026-07-02'});const state=await engine.refresh();eq(state.readOnly,true);eq(state.data.products.length,2);eq(engine.search('Sales today').count,1);const answer=engine.ask('Best selling products');eq(answer.type,'analysis');eq(answer.actionsExecuted,0);const blocked=engine.ask('delete customer');eq(blocked.type,'safety');eq(blocked.actionsExecuted,0);eq(engine.snapshot().chat.length,2);eq(engine.report('ai').readOnly,true);
  const source=fs.readdirSync(__dirname).filter(f=>f.endsWith('.js')&&!f.endsWith('.test.js')).map(f=>fs.readFileSync(path.join(__dirname,f),'utf8')).join('\n');eq(/localStorage\s*\.|fetch\s*\(|XMLHttpRequest|WebSocket\s*\(|createClient\s*\(|SUPABASE_URL|api[_-]?key\s*[:=]\s*['"]/i.test(source),false);eq(/executeSql\s*\(|postAccounting\s*\(|postInventory\s*\(|saveCustomer\s*\(/i.test(source),false);eq(/services[\\/](accounting|inventory|sales|purchases|pos|productionExecution)/i.test(source),false);
  const html=fs.readFileSync(path.join(root,'DigiTronics_v5.html'),'utf8');const pages=['dashboard','business-assistant','sales-insights','inventory-insights','accounting-insights','purchase-insights','customer-insights','supplier-insights','reports-assistant','smart-search','natural-language-query','knowledge-center'];pages.forEach(p=>{ok(html.includes(`data-page="ai-copilot-${p}"`));ok(html.includes(`id="page-ai-copilot-${p}"`));ok(html.includes(`renderAICopilotPage('${p}')`));ok(html.includes(`'ai-copilot-${p}': 'manageUsers'`));});
  const ui=fs.readFileSync(path.join(__dirname,'aiCopilotUi.js'),'utf8');['AI Chat','Analyze — No Execution','Products below minimum stock',"Today's sales",'Invoices awaiting payment','Best selling products','Inactive customers','Profit this month','Most purchased supplier','AI Report','Knowledge Report','Analysis Report','Training Report'].forEach(label=>ok(ui.includes(label),`Missing ${label}`));
  return{tests,aiReadiness:100,intents:10,reports:4,apiCalls:0,sqlExecuted:0,supabaseWrites:0,actionsExecuted:0};
}
if(require.main===module)run().then(v=>console.log(JSON.stringify(v,null,2))).catch(e=>{console.error(e);process.exitCode=1;});module.exports={run};
