(function(root){
  'use strict';const ns=root.OmniAICopilot=root.OmniAICopilot||{};
  function create(options){options=options||{};let data=Object.freeze({products:[],sales:[],invoices:[],customers:[],suppliers:[],purchases:[],expenses:[]}),loadedAt=null,chat=[];const snapshot=()=>Object.freeze({loadedAt,data,chat:Object.freeze([...chat]),sales:ns.SalesInsightEngine.analyze(data),inventory:ns.InventoryInsightEngine.analyze(data),accounting:ns.AccountingInsightEngine.analyze(data),purchases:ns.PurchaseInsightEngine.analyze(data),customers:ns.CustomerSupplierInsightEngine.customers(data),suppliers:ns.CustomerSupplierInsightEngine.suppliers(data),readOnly:true});
    async function refresh(){if(!options.provider||typeof options.provider.readSnapshot!=='function')throw new Error('READ_ONLY_AI_PROVIDER_REQUIRED');const raw=await options.provider.readSnapshot();data=Object.freeze({products:Object.freeze(raw.products||[]),sales:Object.freeze(raw.sales||[]),invoices:Object.freeze(raw.invoices||[]),customers:Object.freeze(raw.customers||[]),suppliers:Object.freeze(raw.suppliers||[]),purchases:Object.freeze(raw.purchases||[]),expenses:Object.freeze(raw.expenses||[])});loadedAt=new Date().toISOString();return snapshot();}
    function ask(text){const security=ns.CopilotSecurityValidator.validate(text);let response;if(!security.safe)response={type:'safety',answer:`I cannot execute ${security.blockedCommand}. I can preview, explain, or recommend instead.`};else{const search=ns.SmartSearchEngine.search(text,data,options.now&&options.now());if(search.intent.id!=='unknown'&&search.intent.id!=='help')response={type:'analysis',answer:search.count?`Found ${search.count} matching result(s).`:'No matching results in the current snapshot.',search};else response={type:'knowledge',answer:ns.KnowledgeCenter.answer(text).answer,article:ns.KnowledgeCenter.answer(text)};}const message=Object.freeze({question:String(text||''),...response,actionsExecuted:0,createdAt:new Date().toISOString()});chat=[...chat,message];return message;}
    return Object.freeze({refresh,snapshot,ask,search:text=>ns.SmartSearchEngine.search(text,data,options.now&&options.now()),report:type=>ns.AIReportBuilder.build(type,snapshot()),lesson:ns.TrainingAssistant.lesson});
  }
  ns.BusinessCopilotEngine=Object.freeze({version:'1.0.0',create});
})(typeof globalThis!=='undefined'?globalThis:window);
