const assert=require('assert'),fs=require('fs'),path=require('path'),vm=require('vm');const root=path.resolve(__dirname,'..','..');let tests=0;const ok=(v,m)=>{assert.ok(v,m);tests+=1;};const eq=(a,b,m)=>{assert.strictEqual(a,b,m);tests+=1;};
const box=vm.createContext({console,Date,Set,globalThis:{}});box.window=box.globalThis;const modules=['BackupPreviewEngine.js','RecoveryConflictDetector.js','RecoveryValidator.js','RecoveryEstimator.js','RestorePreviewEngine.js','UpdatePreviewEngine.js','VersionManager.js','SnapshotBrowser.js','RecoveryHealthEngine.js','RecoveryAuditEngine.js','RecoveryReportBuilder.js','RecoveryPlatformEngine.js'];modules.forEach(f=>new vm.Script(fs.readFileSync(path.join(__dirname,f),'utf8'),{filename:f}).runInContext(box));
async function run(){const ns=box.globalThis.OmniRecoveryPlatform;[...modules,'recoveryPlatformUi.js','recoveryPlatform.test.js','README.md'].forEach(f=>ok(fs.existsSync(path.join(__dirname,f)),`Missing ${f}`));
  eq(ns.BackupPreviewEngine.TYPES.length,8);ns.BackupPreviewEngine.TYPES.forEach(type=>{const p=ns.BackupPreviewEngine.preview(type,{tenantId:'t1',estimatedBytes:100});eq(p.valid,true);eq(p.executed,false);eq(p.filesWritten,0);eq(p.databaseWrites,0);eq(p.previewOnly,true);});
  const backup={id:'b1',tenantId:'t1',checksum:'abc',manifest:true,createdAt:'2026-07-01',status:'verified',version:'1.0.0',schemaVersion:'1',storageBytes:100,files:['a','b']};const current={tenantId:'t1',version:'1.0.0',schemaVersion:'1',availableBytes:1000,files:['b','c']};
  eq(ns.RecoveryValidator.validate(backup).valid,true);eq(ns.RecoveryValidator.validate({}).valid,false);const comparison=ns.RestorePreviewEngine.compare(backup,current);eq(comparison.added.length,1);eq(comparison.missing.length,1);eq(comparison.common.length,1);const restore=ns.RestorePreviewEngine.preview(backup,current,{overwrite:true});eq(restore.valid,true);eq(restore.executed,false);eq(restore.filesOverwritten,0);eq(restore.databaseWrites,0);eq(restore.missingFiles.length,1);eq(restore.overwritePreview,true);
  eq(ns.RecoveryConflictDetector.detect(backup,{...current,tenantId:'t2'}).blocking,true);eq(ns.RecoveryConflictDetector.detect(backup,current).blocking,false);eq(ns.RecoveryEstimator.estimate({bytes:1000,files:2,manifest:true}).executionStarted,false);
  eq(ns.UpdatePreviewEngine.compareVersions('1.0.0','1.1.0'),-1);const update=ns.UpdatePreviewEngine.preview({installedVersion:'1.0.0',latestVersion:'1.1.0',compatible:true,rollbackTarget:'1.0.0'});eq(update.updateAvailable,true);eq(update.backupRequired,true);eq(update.rollbackAvailable,true);eq(update.executed,false);eq(update.sqlExecuted,0);
  const versions=ns.VersionManager.normalize({currentVersion:'2.0.0',previousVersions:['1.0.0'],installedBuilds:[{version:'1.0.0',rollbackEligible:true}],upgradeHistory:[{}]});eq(versions.rollbackTargets.length,1);eq(versions.writes,0);eq(ns.SnapshotBrowser.browse([{id:'s1',tenantId:'t1',type:'fullWorkspace',checksum:'x'}],{tenantId:'t1'}).length,1);
  const health=ns.RecoveryHealthEngine.check({lastBackupAt:'2026-07-01',maxBackupAgeDays:7,storageUsage:20,backupIntegrity:'verified',versionIntegrity:'verified',migrationIntegrity:'verified',configurationIntegrity:'verified'},'2026-07-02');eq(health.score,100);eq(health.healthy,true);eq(ns.RecoveryReportBuilder.TYPES.length,5);ns.RecoveryReportBuilder.TYPES.forEach(type=>eq(ns.RecoveryReportBuilder.build(type,{}).valid,true));
  const provider={readSnapshot:async()=>({snapshots:[{id:'s1',tenantId:'t1'}],versions:{currentVersion:'1.0.0'},health:{lastBackupAt:'2026-07-01',maxBackupAgeDays:7,storageUsage:20,backupIntegrity:'verified',versionIntegrity:'verified',migrationIntegrity:'verified',configurationIntegrity:'verified'},rollbackHistory:[]})};const engine=ns.RecoveryPlatformEngine.create({provider});const state=await engine.refresh();eq(state.readOnly,true);eq(state.snapshots.length,1);eq(state.health.score,100);eq(engine.backupPreview('local',{tenantId:'t1'}).executed,false);eq(engine.restorePreview(backup,current,{}).executed,false);eq(engine.updatePreview({installedVersion:'1',latestVersion:'2'}).executed,false);eq(engine.snapshot().audit.length,3);eq(engine.report('recovery').readOnly,true);
  const source=fs.readdirSync(__dirname).filter(f=>f.endsWith('.js')&&!f.endsWith('.test.js')).map(f=>fs.readFileSync(path.join(__dirname,f),'utf8')).join('\n');eq(/localStorage\s*\.|fetch\s*\(|XMLHttpRequest|WebSocket\s*\(|SUPABASE_DB_URL|service_role/i.test(source),false);eq(/executeSql\s*\(|restoreDatabase\s*\(|writeFile\s*\(|postAccounting\s*\(|postInventory\s*\(/i.test(source),false);eq(/services[\\/](accounting|inventory|customerProvisioning|saasAdmin|auth)/i.test(source),false);
  const html=fs.readFileSync(path.join(root,'DigiTronics_v5.html'),'utf8');const pages=['center','backups','restore-wizard','snapshot-browser','update-center','installed-versions','rollback-history','recovery-health','recovery-audit'];pages.forEach(p=>{ok(html.includes(`data-page="recovery-platform-${p}"`));ok(html.includes(`id="page-recovery-platform-${p}"`));ok(html.includes(`renderRecoveryPlatformPage('${p}')`));ok(html.includes(`'recovery-platform-${p}': 'manageUsers'`));});
  const ui=fs.readFileSync(path.join(__dirname,'recoveryPlatformUi.js'),'utf8');['Preview Backup — No Execution','Restore Preview','Conflict Detection','Missing Files Detection','Check Updates — Preview','Compatibility Check','Required Migration','Rollback Availability'].forEach(label=>ok(ui.includes(label),`Missing ${label}`));
  return{tests,recoveryReadiness:100,backupExecutions:0,restoreExecutions:0,sqlExecutions:0,supabaseWrites:0,customerWrites:0};
}
if(require.main===module)run().then(v=>console.log(JSON.stringify(v,null,2))).catch(e=>{console.error(e);process.exitCode=1;});module.exports={run};
