(function () {
  if (!window.OmniLang) return;
  OmniLang.registerDict('en', {
    "← Business": "← الأعمال",
    "Actions": "إجراءات",
    "Add Center": "إضافة مركز",
    "Add Class": "إضافة صف",
    "Add Course": "إضافة دورة",
    "Add Enrollment": "إضافة تسجيل",
    "Add Program": "إضافة برنامج",
    "Add Student": "إضافة طالب",
    "Add Teacher": "إضافة معلم",
    "Add Session": "إضافة حصة",
    "Address": "العنوان",
    "All": "الكل",
    "Archived": "مؤرشف",
    "Attendance": "الحضور",
    "Attendance Date": "تاريخ الحضور",
    "Attendance records": "سجلات الحضور",
    "Cancel": "إلغاء",
    "Center": "المركز",
    "Center Code": "كود المركز",
    "Centers": "المراكز",
    "Class": "الصف",
    "Class Code": "كود الصف",
    "Classes": "الصفوف",
    "Clear filters": "مسح عوامل التصفية",
    "Close": "إغلاق",
    "Code": "الكود",
    "Confirm": "تأكيد",
    "Course": "الدورة",
    "Course Code": "كود الدورة",
    "Courses": "الدورات",
    "Dashboard": "لوحة التحكم",
    "Date": "التاريخ",
    "Date of Birth": "تاريخ الميلاد",
    "Description": "الوصف",
    "Display Name": "الاسم المعروض",
    "Duration Unit": "وحدة المدة",
    "Duration Value": "قيمة المدة",
    "Duration": "المدة",
    "Education": "التعليم",
    "Education — OmniStore ERP": "التعليم — OmniStore ERP",
    "Edit": "تعديل",
    "Edit Attendance": "تعديل الحضور",
    "Edit Center": "تعديل المركز",
    "Edit Class": "تعديل الصف",
    "Edit Course": "تعديل الدورة",
    "Edit Enrollment": "تعديل التسجيل",
    "Edit Grading": "تعديل التدريج",
    "Edit Program": "تعديل البرنامج",
    "Edit Schedule": "تعديل الجدول",
    "Edit Student": "تعديل الطالب",
    "Edit Teacher": "تعديل المعلم",
    "Email": "البريد الإلكتروني",
    "Employment": "نوع التوظيف",
    "Employment Type": "نوع التوظيف",
    "Enrolled": "تاريخ التسجيل",
    "Enrollment": "التسجيل",
    "Enrollments": "التسجيلات",
    "End Time": "وقت الانتهاء",
    "First Name": "الاسم الأول",
    "From": "من",
    "Gender": "النوع",
    "Grade": "التقدير",
    "Grading": "التدريج",
    "Grading Date": "تاريخ التدريج",
    "IANA time zone, for example Africa/Cairo.": "منطقة زمنية بصيغة IANA، مثل Africa/Cairo.",
    "Info": "معلومات",
    "Last Name": "اسم العائلة",
    "Level": "المستوى",
    "Loading…": "جارٍ التحميل…",
    "Menu": "القائمة",
    "Name": "الاسم",
    "No attendance records for this student.": "لا توجد سجلات حضور لهذا الطالب.",
    "No attendance records yet.": "لا توجد سجلات حضور بعد.",
    "No grades recorded for this student.": "لم يتم تسجيل أي تقدير لهذا الطالب.",
    "No records match the current filters.": "لا توجد سجلات مطابقة لعوامل التصفية الحالية.",
    "No sessions scheduled for these classes.": "لا توجد حصص مجدولة لهذه الصفوف.",
    "No teacher records in this tenant yet.": "لا توجد سجلات معلمين في هذا المستأجر بعد.",
    "No student records in this tenant yet.": "لا توجد سجلات طلاب في هذا المستأجر بعد.",
    "No capabilities reported.": "لم يتم الإبلاغ عن أي إمكانيات.",
    "Notes": "ملاحظات",
    "Phone": "الهاتف",
    "Program": "البرنامج",
    "Program Code": "كود البرنامج",
    "Programs": "البرامج",
    "Qualification": "المؤهل العلمي",
    "Recorded grades": "التقديرات المسجلة",
    "Record Attendance": "تسجيل حضور",
    "Record Grade": "تسجيل تقدير",
    "Refresh": "تحديث",
    "Retry": "إعادة المحاولة",
    "Save": "حفظ",
    "Schedule": "الجدول",
    "Scheduled Date": "تاريخ الحصة",
    "Sessions": "الحصص",
    "Specialization": "التخصص",
    "Start Time": "وقت البداية",
    "Status": "الحالة",
    "Student": "الطالب",
    "Student Code": "كود الطالب",
    "Student Workspace": "مساحة الطالب",
    "Students": "الطلاب",
    "Teacher": "المعلم",
    "Teacher Code": "كود المعلم",
    "Teacher Workspace": "مساحة المعلم",
    "Teachers": "المعلمون",
    "Time": "الوقت",
    "Timezone": "المنطقة الزمنية",
    "To": "إلى",
    "Withdraw": "سحب التسجيل",
    "24-hour wall clock, HH:MM.": "نظام 24 ساعة بصيغة HH:MM.",
    "Must be after the start time.": "يجب أن يكون بعد وقت البداية.",
    "Must be after the start time": "يجب أن يكون بعد وقت البداية",
    "actions.": "إجراءات.",
    "class(es) assigned to this teacher.": "صف (صفوف) مسندة لهذا المعلم.",
    "class(es)": "صف (صفوف)",
    "enrollment(s) for this student.": "تسجيل (تسجيلات) لهذا الطالب.",
    "enrollment(s)": "تسجيل (تسجيلات)",
    "in this tenant": "في هذا المستأجر",
    "records in this tenant": "سجل في هذا المستأجر",
    "records in this tenant.": "سجل في هذا المستأجر.",
    "record": "سجل",
    "records": "سجلات",
    "session(s) across the selected teacher’s classes.": "حصة (حصص) عبر صفوف المعلم المحدد.",
    "session(s)": "حصة (حصص)",
    "the daily register for this student’s active enrollments, oldest first.": "سجل اليومي لتسجيلات هذا الطالب النشطة، الأقدم أولاً.",
    "the platform defines none.": "المنصة لا تعرّف أي منها.",
    "as staff typed it. The platform defines no scale, so no total or comparison is shown.": "كما كتبه الموظفون. المنصة لا تعرّف أي مقياس، لذلك لا يُعرض أي إجمالي أو مقارنة.",
    "Recorded exactly as typed. No scale is defined, so no scale is offered.": "يُسجَّل كما هو مكتوب تماماً. لا يوجد مقياس معرَّف، لذلك لا يُعرض أي مقياس.",
    "Every figure below is a record count for the signed-in tenant, read from the Education services. Nothing here is derived, weighted or compared.": "كل رقم أدناه هو عدد سجلات للمستأجر الحالي، مقروء من خدمات التعليم. لا شيء هنا مُشتق أو مرجَّح أو مُقارَن.",
    "Grading here is descriptive only. A record carries an enrollment, a date, a grade value typed by staff and free-text notes. This page deliberately offers no scale, no totals and no comparison, because the platform defines none.": "التدريج هنا وصفي فقط. يحمل السجل تسجيلاً وتاريخاً وقيمة تقدير يكتبها الموظف وملاحظات نصية. لا توفر هذه الصفحة أي مقياس أو إجماليات أو مقارنة، لأن المنصة لا تعرّف أي منها.",
    "Reported by the Education service itself, so this panel can never overstate the surface.": "مُبلَّغ عنه من خدمة التعليم نفسها، لذلك لا يمكن لهذه اللوحة أن تبالغ في وصف النطاق.",
    "The Education service does not link your signed-in account to a teacher record, so this view is scoped by an explicit teacher selection rather than pretending to know who you are.": "خدمة التعليم لا تربط حسابك المسجَّل بسجل معلم، لذا يكون نطاق هذا العرض باختيار صريح للمعلم بدلاً من الادعاء بمعرفة هويتك.",
    "The Education service does not link your signed-in account to a student record, so this view is scoped by an explicit student selection rather than pretending to know who you are.": "خدمة التعليم لا تربط حسابك المسجَّل بسجل طالب، لذا يكون نطاق هذا العرض باختيار صريح للطالب بدلاً من الادعاء بمعرفة هويتك.",
    "Choose a teacher": "اختر معلمًا",
    "Choose a student": "اختر طالبًا",
    "Choose a teacher to see their classes and sessions.": "اختر معلمًا لعرض صفوفه وحصصه.",
    "Choose a student to see their enrollments and records.": "اختر طالبًا لعرض تسجيلاته وسجلاته.",
    "This student has no enrollments.": "لا يوجد تسجيلات لهذا الطالب.",
    "This teacher has no classes yet.": "لا توجد صفوف لهذا المعلم بعد.",
    "This account is not permitted to use the Education section.": "هذا الحساب غير مصرح له باستخدام قسم التعليم.",
    "Sign in to open the Education section.": "سجّل الدخول لفتح قسم التعليم.",
    "Unable to reach the Education service.": "تعذّر الوصول إلى خدمة التعليم.",
    "Shipped Education capabilities": "إمكانيات التعليم المُطلقة",
    "Education overview": "نظرة عامة على التعليم",
    "Education menu": "قائمة التعليم",
    "Education navigation": "تنقل التعليم",
    "This view is not available.": "هذا العرض غير متاح.",
    "Attendance records by status": "سجلات الحضور حسب الحالة",
    "Raw record counts, read from the attendance service for this tenant.": "أعداد سجلات خام، مقروءة من خدمة الحضور لهذا المستأجر.",
    "Attendance is not readable with this account, so no breakdown is shown.": "الحضور غير قابل للقراءة بهذا الحساب، لذلك لا يُعرض أي تفصيل.",
    "The daily register for this student": "سجل اليومي لهذا الطالب",
    "…": "…",
    "Records in this tenant": "السجلات في هذا المستأجر",
    "Student Code": "كود الطالب",
    "active": "نشط",
    "absent": "غائب",
    "archived": "مؤرشف",
    "contract": "بعقد",
    "days": "أيام",
    "excused": "بعذر",
    "full_time": "دوام كامل",
    "implemented": "مُطبق",
    "inactive": "غير نشط",
    "late": "متأخر",
    "months": "أشهر",
    "not implemented": "غير مُطبق",
    "part_time": "دوام جزئي",
    "present": "حاضر",
    "weeks": "أسابيع",
    "withdrawn": "مسحوب"
  });
}());
