(function () {
  if (!window.OmniLang) return;
  OmniLang.registerDict('en', {
    "← Business": "← الأعمال",
    "Actions": "إجراءات",
    "Add Center": "إضافة مركز",
    "Add Class": "إضافة صف",
    "Add Course": "إضافة دورة",
    "Add Enrollment": "إضافة تسجيل",
    "Add Program": "إضافة برنامج",
    "Add Student": "إضافة طالب",
    "Add Teacher": "إضافة معلم",
    "Add Session": "إضافة حصة",
    "Address": "العنوان",
    "All": "الكل",
    "Archived": "مؤرشف",
    "Attendance": "الحضور",
    "Attendance Date": "تاريخ الحضور",
    "Attendance records": "سجلات الحضور",
    "Cancel": "إلغاء",
    "Center": "المركز",
    "Center Code": "كود المركز",
    "Centers": "المراكز",
    "Center Workspace": "مساحة المركز",
    "Profile": "الملف الشخصي",
    "Progress": "التقدم",
    "Class": "الصف",
    "Class Code": "كود الصف",
    "Classes": "الصفوف",
    "Clear filters": "مسح عوامل التصفية",
    "Close": "إغلاق",
    "Code": "الكود",
    "Confirm": "تأكيد",
    "Count": "العدد",
    "Detail": "التفصيل",
    "Excused": "بعذر",
    "Late": "متأخر",
    "Lessons": "الدروس",
    "Metric": "البيان",
    "Present": "حاضر",
    "Absent": "غائب",
    "Counts below are tenant-wide records, read from the Education services.": "الأعداد أدناه سجلات على مستوى المنشأة، تُقرأ من خدمات التعليم.",
    "enrolled classes": "الصفوف المسجلة",
    "enrolled courses": "الدورات المسجلة",
    "Raw read-only counts from the Education service for this student. No percentage, score or grade is derived.": "أعداد قراءة فقط من خدمة التعليم لهذا الطالب. لا تُشتق أي نسبة أو درجة.",
    "scheduled for enrolled classes": "مجدولة لصفوف الطالب المسجلة",
    "Some figures are not readable with this account.": "بعض الأعداد غير قابلة للقراءة بهذا الحساب.",
    "the canonical model has no lesson entity": "النموذج الأساسي لا يتضمن كيانًا للدروس",
    "Course": "الدورة",
    "Course Code": "كود الدورة",
    "Courses": "الدورات",
    "Dashboard": "لوحة التحكم",
    "Date": "التاريخ",
    "Date of Birth": "تاريخ الميلاد",
    "Description": "الوصف",
    "Display Name": "الاسم المعروض",
    "Duration Unit": "وحدة المدة",
    "Duration Value": "قيمة المدة",
    "Duration": "المدة",
    "Education": "التعليم",
    "Education — OmniStore ERP": "التعليم — OmniStore ERP",
    "Edit": "تعديل",
    "Edit Attendance": "تعديل الحضور",
    "Edit Center": "تعديل المركز",
    "Edit Class": "تعديل الصف",
    "Edit Course": "تعديل الدورة",
    "Edit Enrollment": "تعديل التسجيل",
    "Edit Grading": "تعديل التدريج",
    "Edit Program": "تعديل البرنامج",
    "Edit Schedule": "تعديل الجدول",
    "Edit Student": "تعديل الطالب",
    "Edit Teacher": "تعديل المعلم",
    "Email": "البريد الإلكتروني",
    "Employment": "نوع التوظيف",
    "Employment Type": "نوع التوظيف",
    "Enrolled": "تاريخ التسجيل",
    "Enrollment": "التسجيل",
    "Enrollments": "التسجيلات",
    "End Time": "وقت الانتهاء",
    "First Name": "الاسم الأول",
    "From": "من",
    "Gender": "النوع",
    "Grade": "التقدير",
    "Grading": "التدريج",
    "Grading Date": "تاريخ التدريج",
    "IANA time zone, for example Africa/Cairo.": "منطقة زمنية بصيغة IANA، مثل Africa/Cairo.",
    "Info": "معلومات",
    "Last Name": "اسم العائلة",
    "Level": "المستوى",
    "Loading…": "جارٍ التحميل…",
    "Menu": "القائمة",
    "Name": "الاسم",
    "No attendance records for this student.": "لا توجد سجلات حضور لهذا الطالب.",
    "No attendance records yet.": "لا توجد سجلات حضور بعد.",
    "No grades recorded for this student.": "لم يتم تسجيل أي تقدير لهذا الطالب.",
    "No records match the current filters.": "لا توجد سجلات مطابقة لعوامل التصفية الحالية.",
    "No sessions scheduled for these classes.": "لا توجد حصص مجدولة لهذه الصفوف.",
    "No teacher records in this tenant yet.": "لا توجد سجلات معلمين في هذا المستأجر بعد.",
    "No student records in this tenant yet.": "لا توجد سجلات طلاب في هذا المستأجر بعد.",
    "No capabilities reported.": "لم يتم الإبلاغ عن أي إمكانيات.",
    "Notes": "ملاحظات",
    "Phone": "الهاتف",
    "Program": "البرنامج",
    "Program Code": "كود البرنامج",
    "Programs": "البرامج",
    "Qualification": "المؤهل العلمي",
    "Recorded grades": "التقديرات المسجلة",
    "Record Attendance": "تسجيل حضور",
    "Record Grade": "تسجيل تقدير",
    "Refresh": "تحديث",
    "Retry": "إعادة المحاولة",
    "Save": "حفظ",
    "Schedule": "الجدول",
    "Scheduled Date": "تاريخ الحصة",
    "Sessions": "الحصص",
    "Specialization": "التخصص",
    "Start Time": "وقت البداية",
    "Status": "الحالة",
    "Student": "الطالب",
    "Student Code": "كود الطالب",
    "Student Workspace": "مساحة الطالب",
    "Students": "الطلاب",
    "Teacher": "المعلم",
    "Teacher Code": "كود المعلم",
    "Teacher Workspace": "مساحة المعلم",
    "Teachers": "المعلمون",
    "Time": "الوقت",
    "Timezone": "المنطقة الزمنية",
    "To": "إلى",
    "Withdraw": "سحب التسجيل",
    "24-hour wall clock, HH:MM.": "نظام 24 ساعة بصيغة HH:MM.",
    "Must be after the start time.": "يجب أن يكون بعد وقت البداية.",
    "Must be after the start time": "يجب أن يكون بعد وقت البداية",
    "actions.": "إجراءات.",
    "class(es) assigned to this teacher.": "صف (صفوف) مسندة لهذا المعلم.",
    "class(es)": "صف (صفوف)",
    "enrollment(s) for this student.": "تسجيل (تسجيلات) لهذا الطالب.",
    "enrollment(s)": "تسجيل (تسجيلات)",
    "in this tenant": "في هذا المستأجر",
    "records in this tenant": "سجل في هذا المستأجر",
    "records in this tenant.": "سجل في هذا المستأجر.",
    "record": "سجل",
    "records": "سجلات",
    "session(s) across the selected teacher’s classes.": "حصة (حصص) عبر صفوف المعلم المحدد.",
    "session(s)": "حصة (حصص)",
    "the daily register for this student’s active enrollments, oldest first.": "سجل اليومي لتسجيلات هذا الطالب النشطة، الأقدم أولاً.",
    "the platform defines none.": "المنصة لا تعرّف أي منها.",
    "as staff typed it. The platform defines no scale, so no total or comparison is shown.": "كما كتبه الموظفون. المنصة لا تعرّف أي مقياس، لذلك لا يُعرض أي إجمالي أو مقارنة.",
    "Recorded exactly as typed. No scale is defined, so no scale is offered.": "يُسجَّل كما هو مكتوب تماماً. لا يوجد مقياس معرَّف، لذلك لا يُعرض أي مقياس.",
    "Every figure below is a record count for the signed-in tenant, read from the Education services. Nothing here is derived, weighted or compared.": "كل رقم أدناه هو عدد سجلات للمستأجر الحالي، مقروء من خدمات التعليم. لا شيء هنا مُشتق أو مرجَّح أو مُقارَن.",
    "Grading here is descriptive only. A record carries an enrollment, a date, a grade value typed by staff and free-text notes. This page deliberately offers no scale, no totals and no comparison, because the platform defines none.": "التدريج هنا وصفي فقط. يحمل السجل تسجيلاً وتاريخاً وقيمة تقدير يكتبها الموظف وملاحظات نصية. لا توفر هذه الصفحة أي مقياس أو إجماليات أو مقارنة، لأن المنصة لا تعرّف أي منها.",
    "Reported by the Education service itself, so this panel can never overstate the surface.": "مُبلَّغ عنه من خدمة التعليم نفسها، لذلك لا يمكن لهذه اللوحة أن تبالغ في وصف النطاق.",
    "The Education service does not link your signed-in account to a teacher record, so this view is scoped by an explicit teacher selection rather than pretending to know who you are.": "خدمة التعليم لا تربط حسابك المسجَّل بسجل معلم، لذا يكون نطاق هذا العرض باختيار صريح للمعلم بدلاً من الادعاء بمعرفة هويتك.",
    "The Education service does not link your signed-in account to a student record, so this view is scoped by an explicit student selection rather than pretending to know who you are.": "خدمة التعليم لا تربط حسابك المسجَّل بسجل طالب، لذا يكون نطاق هذا العرض باختيار صريح للطالب بدلاً من الادعاء بمعرفة هويتك.",
    "Choose a teacher": "اختر معلمًا",
    "Choose a student": "اختر طالبًا",
    "Choose a teacher to see their classes and sessions.": "اختر معلمًا لعرض صفوفه وحصصه.",
    "Choose a student to see their enrollments and records.": "اختر طالبًا لعرض تسجيلاته وسجلاته.",
    "This student has no enrollments.": "لا يوجد تسجيلات لهذا الطالب.",
    "This teacher has no classes yet.": "لا توجد صفوف لهذا المعلم بعد.",
    "This account is not permitted to use the Education section.": "هذا الحساب غير مصرح له باستخدام قسم التعليم.",
    "Sign in to open the Education section.": "سجّل الدخول لفتح قسم التعليم.",
    "Unable to reach the Education service.": "تعذّر الوصول إلى خدمة التعليم.",
    "Shipped Education capabilities": "إمكانيات التعليم المُطلقة",
    "Education overview": "نظرة عامة على التعليم",
    "Education menu": "قائمة التعليم",
    "Education navigation": "تنقل التعليم",
    "This view is not available.": "هذا العرض غير متاح.",
    "Attendance records by status": "سجلات الحضور حسب الحالة",
    "Raw record counts, read from the attendance service for this tenant.": "أعداد سجلات خام، مقروءة من خدمة الحضور لهذا المستأجر.",
    "Attendance is not readable with this account, so no breakdown is shown.": "الحضور غير قابل للقراءة بهذا الحساب، لذلك لا يُعرض أي تفصيل.",
    "The daily register for this student": "سجل اليومي لهذا الطالب",
    "Class roster": "قائمة طلاب الصف",
    "Roster": "قائمة طلاب الصف",
    "Class details": "تفاصيل الصف",
    "No class records in this tenant yet.": "لا توجد سجلات صفوف في هذا المستأجر بعد.",
    "Choose a class to see its roster.": "اختر صفاً لعرض قائمة طلابه.",
    "Choose a class": "اختر صفاً",
    "Record": "السجل",
    "No students are enrolled in this class yet.": "لا يوجد طلاب مسجلون في هذا الصف بعد.",
    "No enrolled student matches this search.": "لا يوجد طالب مسجل يطابق هذا البحث.",
    "Search students": "البحث عن الطلاب",
    "enrolled student": "طالب مسجل",
    "enrolled students": "طلاب مسجلون",
    "Withdrawn": "مسحوب",
    "Take attendance": "تسجيل الحضور",
    "Class register": "سجل الصف",
    "Class Register": "سجل الصف",
    "Mark all present": "تعليم الكل حاضر",
    "Save all": "حفظ الكل",
    "Save settings": "حفظ الإعدادات",
    "Not set": "غير محدد",
    "— not set —": "— غير محدد —",
    "Total": "الإجمالي",
    "Already recorded": "مسجل مسبقاً",
    "correction": "تصحيح",
    "new": "جديد",
    "Day": "يوم",
    "Week": "أسبوع",
    "Agenda": "جدول زمني",
    "View": "العرض",
    "Earlier range": "نطاق أسبق",
    "Later range": "نطاق لاحق",
    "Today": "اليوم",
    "No sessions": "لا توجد حصص",
    "No sessions are scheduled in this range.": "لا توجد حصص مجدولة في هذه الفترة.",
    "session": "حصة",
    "sessions": "حصص",
    "between": "بين",
    "and": "و",
    "Mon": "الاثنين",
    "Tue": "الثلاثاء",
    "Wed": "الأربعاء",
    "Thu": "الخميس",
    "Fri": "الجمعة",
    "Sat": "السبت",
    "Sun": "الأحد",
    "Reports": "التقارير",
    "Attendance report": "تقرير الحضور",
    "Grading report": "تقرير الدرجات",
    "Session report": "تقرير الحصص",
    "Start": "البداية",
    "End": "النهاية",
    "Every row is an attendance record that already exists in this tenant, read over a date range. The figures above the table are counts of those rows: no rate, share, ratio or average is derived from them.": "كل صف سجل حضور موجود بالفعل في هذا المستأجر، مقروء ضمن نطاق تاريخي. الأرقام أعلى الجدول هي أعداد هذه السجلات: لا يُشتق منها أي نسبة أو حصة أو معامل أو متوسط.",
    "Every row is a recorded grade that already exists in this tenant, read over a date range. Each grade is shown exactly as staff typed it: the platform defines no scale, so no scale, total, comparison or conversion appears here.": "كل صف درجة مسجلة موجودة بالفعل في هذا المستأجر، مقروءة ضمن نطاق تاريخي. تُعرض كل درجة تماماً كما كتبها الموظفون: المنصة لا تُعرّف أي مقياس، لذا لا يظهر هنا أي مقياس أو مجموع أو مقارنة أو تحويل.",
    "Every row is a session that already exists in this tenant, read over a date range. There is no recurring timetable, no room and no capacity anywhere in the service, so none is shown: an empty range is empty because nothing was scheduled.": "كل صف حصة موجودة بالفعل في هذا المستأجر، مقروءة ضمن نطاق تاريخي. لا يوجد جدول متكرر ولا قاعة ولا سعة في الخدمة، لذا لا يُعرض أي منها: النطاق الفارغ فارغ لعدم جدولة أي شيء.",
    "Settings": "الإعدادات",
    "Calendar": "التقويم",
    "Schedule calendar": "تقويم الجدول",
    "Education settings": "إعدادات التعليم",
    "Academic Year": "العام الدراسي",
    "Academic Years": "الأعوام الدراسية",
    "Add Academic Year": "إضافة عام دراسي",
    "Terms": "الفصول الدراسية",
    "Add Term": "إضافة فصل دراسي",
    "Term": "فصل دراسي",
    "Subjects": "المواد الدراسية",
    "Add Subject": "إضافة مادة دراسية",
    "Subject": "مادة دراسية",
    "Groups": "المجموعات",
    "Add Group": "إضافة مجموعة",
    "Group": "مجموعة",
    "Free text, exactly as the Education service stores it.": "نص حر، تماماً كما تخزنه خدمة التعليم.",
    "Free text, for example EGP. The service defines no currency list.": "نص حر، مثل EGP. لا تُعرّف الخدمة قائمة عملات.",
    "Free text": "نص حر",
    "These are the only three settings the Education service accepts. They are tenant scoped, saved through the existing pack endpoint, and nothing else about the section is configurable here.": "هذه هي الإعدادات الثلاثة الوحيدة التي تقبلها خدمة التعليم. فهي خاصة بالمستأجر، وتُحفظ عبر نقطة الحزمة الحالية، ولا شيء آخر في القسم قابل للتهيئة هنا.",
    "Saving…": "جارٍ الحفظ…",
    "Settings saved.": "تم حفظ الإعدادات.",
    "Export CSV": "تصدير CSV",
    "records exported.": "سجلات تم تصديرها.",
    "record exported.": "سجل تم تصديره.",
    "exported.": "تم تصديرها.",
    "There is nothing to export for the current filters.": "لا توجد سجلات لتصديرها بعوامل التصفية الحالية.",
    "Class details read-only.": "تفاصيل الصف للعرض فقط.",
    "Mark a whole class in one save. Every student needs an explicit status; nothing is marked for you. A day that is already recorded is loaded here so you can correct it through the same rules the service already applies.": "سجّل الصف كاملاً بحفظ واحد. يحتاج كل طالب إلى حالة صريحة؛ لا يُعلَّم شيء نيابة عنك. يُحمَّل هنا اليوم المسجل مسبقاً حتى تصححه بالقواعد نفسها التي تطبقها الخدمة.",
    "Every entry below is a session that already exists in this tenant, read over a date range. There is no recurring timetable here: an empty day is empty because nothing was scheduled, not because a template is missing.": "كل عنصر أدناه حصة موجودة بالفعل في هذا المستأجر، مقروءة ضمن نطاق تاريخي. لا يوجد جدول متكرر هنا: اليوم الفارغ فارغ لعدم جدولة أي شيء، لا نقص في قالب.",
    "Choose a class and a date to mark the register.": "اختر صفاً وتاريخاً لتسجيل الحضور.",
    "No students are enrolled in this class, so there is no register to mark.": "لا يوجد طلاب مسجلون في هذا الصف، لذا لا يوجد سجل لتسجيل الحضور فيه.",
    "student(s) still have no status. Mark every student before saving.": "طالب ما زال بلا حالة. حدّد حالة كل طالب قبل الحفظ.",
    "recorded": "تم التسجيل",
    "corrected": "تم التصحيح",
    "failed": "فشل",
    "…": "…",
    "Records in this tenant": "السجلات في هذا المستأجر",
    "Student Code": "كود الطالب",
    "active": "نشط",
    "absent": "غائب",
    "archived": "مؤرشف",
    "contract": "بعقد",
    "days": "أيام",
    "excused": "بعذر",
    "full_time": "دوام كامل",
    "implemented": "مُطبق",
    "inactive": "غير نشط",
    "late": "متأخر",
    "months": "أشهر",
    "not implemented": "غير مُطبق",
    "part_time": "دوام جزئي",
    "present": "حاضر",
    "weeks": "أسابيع",
    "withdrawn": "مسحوب",
    "Bookings": "الحجوزات",
    "Ratings": "التقييمات",
    "Add Booking": "إضافة حجز",
    "Add Rating": "إضافة تقييم",
    "Fee": "السعر",
    "Score": "الدرجة",
    "Comment": "التعليق",
    "Complete": "إتمام",
    "requested": "مطلوب",
    "confirmed": "مؤكد",
    "completed": "مكتمل",
    "cancelled": "ملغى",
    "This account is linked to a teacher record, so the workspace opens on that record. The picker below stays explicit and can be changed at any time.": "مرتبط هذا الحساب بسجل معلّم، لذا تفتح مساحة العمل على ذلك السجل. القائمة أدناه تبقى صريحة ويمكن تغييرها في أي وقت.",
    "Class price as a plain decimal amount, for example 1500 or 1500.50. Leave empty for no fee.": "سعر الفصل كقيمة عشرية بسيطة، مثال 1500 أو 1500.50. اتركه فارغاً لعدم وجود سعر."
  });
}());
