# ============================================================================
# OmniStore Windows Installer (First Company)
# ============================================================================
# Installs a release archive (scripts/build-release.js output) on a clean
# Windows machine:
#
#   powershell -ExecutionPolicy Bypass -File scripts\install-windows.ps1 `
#     -ZipPath .\releases\OmniStore-1.0.0.zip [-InstallDir C:\OmniStore] [-Port 3001]
#
# Layout:
#   <InstallDir>\app        application files (from the release zip)
#   <InstallDir>\data       COMPANY DATA (never touched by updates)
#   <InstallDir>\backups    update backups / downloads
#   <InstallDir>\logs       application logs
#   <InstallDir>\.env       generated configuration (random secrets)
#
# Runs the backend as a Windows service (NSSM) when available; otherwise
# falls back to a startup shortcut. Then health-checks and prints the URL.
# The updater (in-app update rail) stops/starts the service via
# UPDATE_STOP_COMMAND / UPDATE_START_COMMAND (net stop/start OmniStoreBackend).
# ============================================================================

param(
  [Parameter(Mandatory = $true)][string]$ZipPath,
  [string]$InstallDir = 'C:\OmniStore',
  [int]$Port = 3001,
  [string]$ServiceName = 'OmniStoreBackend'
)

$ErrorActionPreference = 'Stop'

# Normalize to an absolute path: guards against drive-relative input (e.g.
# 'C:OmniStore' when invoked from Git Bash, which strips backslashes) so every
# generated path in .env is a real absolute Windows path.
$InstallDir = [System.IO.Path]::GetFullPath($InstallDir)

function New-RandomSecret([int]$bytes = 48) {
  $buf = New-Object byte[] $bytes
  $rng = New-Object System.Security.Cryptography.RNGCryptoServiceProvider
  $rng.GetBytes($buf)
  $rng.Dispose()
  return [Convert]::ToBase64String($buf)
}

Write-Host '=== OmniStore Windows Installer ===' -ForegroundColor Cyan
if (-not (Test-Path $ZipPath)) { throw "Release zip not found: $ZipPath" }

# 1. Node.js check
$nodeBin = (Get-Command node -ErrorAction SilentlyContinue)
if (-not $nodeBin) { throw 'Node.js 18+ is required. Install it first: https://nodejs.org (winget install OpenJS.NodeJS.LTS)' }
$nodeVer = & node -v
Write-Host "Node.js: $nodeVer"
if ([int](($nodeVer -replace '[^0-9.]', '').Split('.')[0]) -lt 18) { throw 'Node.js 18+ is required.' }

# 2. Layout
$appDir  = Join-Path $InstallDir 'app'
$dataDir = Join-Path $InstallDir 'data'
$bakDir  = Join-Path $InstallDir 'backups'
$logDir  = Join-Path $InstallDir 'logs'
foreach ($d in @($appDir, $dataDir, $bakDir, $logDir)) { New-Item -ItemType Directory -Force -Path $d | Out-Null }

# 3. Extract release (application files only; data dir is separate)
Write-Host 'Extracting application files...'
$stage = Join-Path $InstallDir '.stage-extract'
if (Test-Path $stage) { Remove-Item $stage -Recurse -Force }
Expand-Archive -Path $ZipPath -DestinationPath $stage -Force
# move contents into app dir
Get-ChildItem $stage | ForEach-Object { Move-Item $_.FullName (Join-Path $appDir $_.Name) -Force }
Remove-Item $stage -Recurse -Force

if (-not (Test-Path (Join-Path $appDir 'backend\server.js'))) { throw 'Release zip does not look like an OmniStore release (backend\server.js missing).' }

# 4. Configuration (never print the secrets)
Write-Host 'Generating configuration...'
$envFile = Join-Path $InstallDir '.env'
$envContent = @"
# Generated by install-windows.ps1 - never commit this file.
NODE_ENV=production
PORT=$Port
JWT_SECRET=$(New-RandomSecret)
JWT_REFRESH_SECRET=$(New-RandomSecret)
AUTH_REQUIRED=true
DIGITRONICS_DATA_DIR=$dataDir
LOG_FILE=$(Join-Path $logDir 'backend.log')

# Multi-tenant / company isolation (production first-company config)
ENABLE_MULTI_COMPANY_LOGIN=true
ENABLE_TENANT_USER_MEMBERSHIP=true
ENABLE_TENANT_ROLES=true
ENABLE_TENANT_CARRY=true
ENABLE_TENANT_FILTERING=true
ENABLE_TENANT_METADATA=true
ENABLE_TENANT_SALES_ISOLATION=true
ENABLE_TENANT_PURCHASES_ISOLATION=true

UPDATE_ENABLED=true
UPDATE_MANIFEST_PATH=$(Join-Path $dataDir 'updateManifest.json')
UPDATE_START_CWD=$InstallDir
UPDATE_STOP_COMMAND=
UPDATE_START_COMMAND=
CORS_ORIGINS=
"@
Set-Content -Path $envFile -Value $envContent -Encoding ascii
Write-Host "Configuration written to $envFile (secrets are random; file is readable only on this machine)."

# 5. Service registration
$nssm = Get-Command nssm.exe -ErrorAction SilentlyContinue
if ($nssm) {
  Write-Host "Registering Windows service '$ServiceName' via NSSM..."
  & $nssm.Source install $ServiceName (Join-Path (Split-Path $nodeBin.Source) 'node.exe') (Join-Path $appDir 'backend\server.js') | Out-Null
  & $nssm.Source set $ServiceName AppDirectory $InstallDir | Out-Null
  & $nssm.Source set $ServiceName AppStdout (Join-Path $logDir 'service.log') | Out-Null
  & $nssm.Source set $ServiceName AppStderr (Join-Path $logDir 'service.err.log') | Out-Null
  & $nssm.Source set $ServiceName Start SERVICE_AUTO_START | Out-Null
  & $nssm.Source start $ServiceName | Out-Null
  # Service-mode update control: the in-app updater stops/starts the service.
  $envFile = Join-Path $InstallDir '.env'
  $lines = Get-Content $envFile
  $lines = $lines -replace '^UPDATE_STOP_COMMAND=.*$', "UPDATE_STOP_COMMAND=net stop $ServiceName"
  $lines = $lines -replace '^UPDATE_START_COMMAND=.*$', "UPDATE_START_COMMAND=net start $ServiceName"
  Set-Content -Path $envFile -Value $lines -Encoding ascii
  $serviceMode = "service '$ServiceName'"
} else {
  Write-Host 'NSSM not found - registering a startup shortcut instead (service recommended: winget install NSSM).'
  # IMPORTANT: never redirect stdout to the logger's file (LOG_FILE). The
  # redirection holds the file open, and the backend's own logger then fails
  # with EBUSY. The backend writes its log via LOG_FILE itself.
  $startupDir = [Environment]::GetFolderPath('Startup')
  $cmd = @"
@echo off
cd /d "$InstallDir"
start /min "OmniStore Backend" powershell -NoProfile -WindowStyle Hidden -Command "cd '$InstallDir'; node app\backend\server.js"
"@
  $cmdPath = Join-Path $startupDir 'OmniStore-Backend.cmd'
  Set-Content -Path $cmdPath -Value $cmd -Encoding ascii
  Start-Process powershell -ArgumentList @('-NoProfile', '-WindowStyle', 'Hidden', '-Command', "cd '$InstallDir'; node app\backend\server.js")
  # Without a service, the in-app updater must still be able to STOP the app
  # before swapping the application directory (otherwise the old process keeps
  # port $Port and the new version fails its health check). Write a tiny
  # stop-backend.cmd that kills whatever is listening on the app port, and
  # point UPDATE_STOP_COMMAND at it. The file lives OUTSIDE the app dir, so it
  # survives updates. UPDATE_START_COMMAND stays empty: the updater starts the
  # new version itself (node backend/server.js with UPDATE_START_CWD).
  $stopScript = Join-Path $InstallDir 'stop-backend.cmd'
  $stopCmd = "@echo off`r`npowershell -NoProfile -Command `"Get-NetTCPConnection -LocalPort $Port -State Listen -ErrorAction SilentlyContinue | ForEach-Object { Stop-Process -Id `$_.OwningProcess -Force -ErrorAction SilentlyContinue }`"`r`n"
  Set-Content -Path $stopScript -Value $stopCmd -Encoding ascii
  $lines = Get-Content $envFile
  $lines = $lines -replace '^UPDATE_STOP_COMMAND=.*$', "UPDATE_STOP_COMMAND=$stopScript"
  Set-Content -Path $envFile -Value $lines -Encoding ascii
  $serviceMode = "startup shortcut ($cmdPath)"
}

# 6. Health check
$url = "http://127.0.0.1:$Port/api/v1/health"
Write-Host "Waiting for $url ..."
$healthy = $false
for ($i = 0; $i -lt 40; $i++) {
  Start-Sleep -Milliseconds 750
  try {
    $r = Invoke-WebRequest -Uri $url -UseBasicParsing -TimeoutSec 3
    if ($r.StatusCode -eq 200) { $healthy = $true; break }
  } catch {}
}
if (-not $healthy) { throw "Backend did not become healthy at $url - check $logDir" }

Write-Host ''
Write-Host '=== INSTALLATION COMPLETE ===' -ForegroundColor Green
Write-Host "Application : $appDir"
Write-Host "Data folder : $dataDir   (company data - never touched by updates)"
Write-Host "Backups     : $bakDir"
Write-Host "Logs        : $logDir"
Write-Host "Run mode    : $serviceMode"
Write-Host "URL         : http://localhost:$Port  (install the PWA from the browser for the desktop app)"
Write-Host 'First company: see GO_LIVE.md (npm run provision -- --company-name ... )'
