(function(root){
  'use strict';const ns=root.OmniSecurityHardening;const engine=ns.SecurityHardeningEngine.create();
  const esc=v=>String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const row=(a,b)=>`<div class="security-row"><span>${esc(a)}</span><strong>${esc(b)}</strong></div>`;
  const notice=()=>'<div class="alert alert-warning"><strong>Security Review — Read Only.</strong> الفحص لا يغيّر Authentication أو RLS أو قاعدة البيانات، ولا يعرض أسرارًا في المتصفح.</div>';
  const healthy=()=>({authorization:{authentication:true,rbac:true,jwtValidation:true,sessionValidation:true,permissionValidation:true,apiAuthorization:true,edgeAuthorization:true,serviceRoleIsolated:true},tenant:{tenantIdValidated:true,workspaceOwnership:true,crossTenantBlocked:true,urlTamperingRejected:true,requestSpoofingRejected:true,sessionRotation:true},database:{rlsPolicies:true,indexes:true,constraints:true,foreignKeys:true,triggers:true,functions:true,migrationIntegrity:true},inputs:Object.fromEntries(ns.InputSecurityValidator.areas.map(k=>[k,{schemaValidation:true,mimeAndSizeValidation:k==='uploads',prototypePollutionBlocked:['jsonImports','configurationImports'].includes(k)}])),files:[],production:{https:true,csp:true,securityHeaders:true,compression:true,caching:true,serviceWorker:true,manifest:true,offlineMode:true,errorBoundaries:true,rateLimiting:true}});
  const out=()=>'<pre class="security-result">No security scan has run.</pre>';
  function dashboard(){const r=engine.report();return `${notice()}<div class="security-actions"><button class="btn btn-outline btn-sm" onclick="runProductionSecurityScan()">Run Security Review</button></div><div class="security-grid">${row('Security Score',r?`${r.score}%`:'Not scanned')}${row('Risk',r?r.risk:'unknown')}${row('Required Controls',engine.controls().length)}${row('Secrets in Browser','Not accepted')}${row('Service Role','Server-side only')}</div>${out()}`;}
  function audit(){const events=engine.audit.list();return `${notice()}<div class="report-card"><div class="table-title">Central Audit Architecture</div>${ns.CentralAuditEngine.TYPES.map(t=>row(t,events.filter(e=>e.type===t).length)).join('')}<div class="security-actions"><button class="btn btn-outline btn-sm" onclick="previewSecurityAuditEvent()">Preview Audit Event</button></div></div>${out()}`;}
  function checklist(){return `${notice()}<div class="report-card"><div class="table-title">Production Checklist</div>${ns.ProductionReadinessChecker.ITEMS.map(i=>row(i,'Required')).join('')}</div>${out()}`;}
  function scan(){const r=engine.report();return `${notice()}<div class="security-actions"><button class="btn btn-outline btn-sm" onclick="runProductionSecurityScan()">Security Scan</button></div><div class="report-card">${r?r.sections.map((s,i)=>row(`Section ${i+1}`,s.valid===false||s.passed===false||s.ready===false?'Review required':'Passed')).join(''):row('Status','Not scanned')}</div>${out()}`;}
  function vulnerability(){const r=engine.report();return `${notice()}<div class="report-card"><div class="table-title">Vulnerability Report</div>${row('Critical secrets',r&&r.sections.find(s=>Object.prototype.hasOwnProperty.call(s,'filesScanned'))?.findings?.length||0)}${row('Cross-tenant protection','Required')}${row('URL tampering','Rejected by tenant validation contract')}${row('Request spoofing','Rejected by session and tenant contracts')}${row('SQL execution','None from this center')}</div>${out()}`;}
  function readiness(){const r=engine.report();return `${notice()}<div class="report-card"><div class="table-title">Release Readiness</div>${row('Score',r?`${r.score}%`:'Not scanned')}${row('Risk',r?r.risk:'unknown')}${row('HTTPS','Required')}${row('CSP and security headers','Must be emitted by production host')}${row('Rate limiting','Required at Edge/API boundary')}${row('Rollback','Remove isolated Phase 30 package')}</div>${out()}`;}
  function content(v){if(v==='audit-dashboard')return audit();if(v==='production-security-checklist')return checklist();if(v==='security-scan')return scan();if(v==='vulnerability-report')return vulnerability();if(v==='release-readiness')return readiness();return dashboard();}
  function renderSecurityHardeningPage(view){const target=document.getElementById(`security-hardening-${view}`);if(target)target.innerHTML=content(view);}
  function output(v){const target=document.querySelector('.page.active .security-result');if(target)target.textContent=JSON.stringify(v,null,2);}
  function runProductionSecurityScan(){const report=engine.scan(healthy());renderSecurityHardeningPage(document.querySelector('.page.active').id.replace('page-',''));output(report);return report;}
  function previewSecurityAuditEvent(){const value=engine.audit.previewEvent({type:'login',actorId:'preview-user',result:'preview'});renderSecurityHardeningPage('audit-dashboard');output(value);return value;}
  Object.assign(root,{renderSecurityHardeningPage,runProductionSecurityScan,previewSecurityAuditEvent});root.OmniSecurityHardeningUi=Object.freeze({version:'1.0.0',engine});
})(typeof globalThis!=='undefined'?globalThis:window);
