(function(root){
  'use strict';const ns=root.OmniAICopilot;const engine=ns.BusinessCopilotEngine.create({provider:{readSnapshot:async()=>({products:[],sales:[],invoices:[],customers:[],suppliers:[],purchases:[],expenses:[]})}});
  const esc=v=>String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const row=(a,b)=>`<div class="ai-copilot-row"><span>${esc(a)}</span><strong>${esc(typeof b==='object'?JSON.stringify(b):b)}</strong></div>`;const title=x=>`<div class="table-title">${esc(x)}</div>`;
  const notice=()=>'<div class="alert alert-info"><strong>AI Business Copilot — Read Only.</strong> يحلل ويشرح ويقترح فقط. لا ينفذ أوامر، ولا يستخدم API Key أو SQL أو Supabase writes.</div>';const out=()=>'<pre class="ai-copilot-result">No AI analysis has run.</pre>';
  function chat(){const messages=engine.snapshot().chat;return `<div class="report-card">${title('AI Chat')}<div class="ai-chat-log">${messages.length?messages.map(x=>`<div class="ai-message"><strong>You:</strong> ${esc(x.question)}<br><strong>Copilot:</strong> ${esc(x.answer)}</div>`).join(''):'<div class="ai-message">Ask about reports, errors, pages, stock, sales, customers, profit, suppliers, or training.</div>'}</div><div class="form-group" style="margin-top:12px"><label>Ask Copilot</label><textarea id="aiCopilotQuestion" placeholder="مثال: المنتجات الأقل من الحد الأدنى"></textarea></div><button class="btn btn-outline btn-sm" onclick="askBusinessCopilot()">Analyze — No Execution</button></div>`;}
  function dashboard(){const s=engine.snapshot();return `${notice()}<div class="ai-copilot-actions"><button class="btn btn-outline btn-sm" onclick="refreshBusinessCopilot()">Refresh Read-only Context</button></div><div class="ai-copilot-grid"><div class="report-card">${title('Sales')}${row('Total',s.sales.totalSales)}${row('Gross Profit',s.sales.grossProfit)}</div><div class="report-card">${title('Inventory')}${row('Low Stock',s.inventory.lowStock.length)}${row('Dead Stock',s.inventory.deadStock.length)}</div><div class="report-card">${title('Customers')}${row('Total',s.customers.total)}${row('Inactive',s.customers.inactive.length)}</div><div class="report-card">${title('Purchases')}${row('Total',s.purchases.totalPurchases)}${row('Recommendations',s.purchases.recommendations.length)}</div></div>${chat()}${out()}`;}
  function assistant(){return `${notice()}${chat()}${out()}`;}
  function insight(type){const s=engine.snapshot(),value=type==='sales'?s.sales:type==='inventory'?s.inventory:type==='accounting'?s.accounting:type==='purchases'?s.purchases:type==='customers'?s.customers:s.suppliers;return `${notice()}<div class="report-card">${title(`${type} Insights`)}${Object.entries(value).map(([k,v])=>row(k,v)).join('')}</div>${out()}`;}
  function reports(){return `${notice()}<div class="ai-copilot-grid">${[['ai','AI Report'],['knowledge','Knowledge Report'],['analysis','Analysis Report'],['training','Training Report']].map(([type,label])=>`<div class="report-card">${title(label)}<button class="btn btn-outline btn-sm" onclick="previewAIReport('${type}')">Generate Summary</button></div>`).join('')}</div><div class="report-card" style="margin-top:14px">${title('Available Summaries')}${row('Executive Reports','Advisory summary')}${row('Customer Reports','Behavior summary')}${row('Inventory Summaries','Stock and movement summary')}${row('Accounting Summaries','Non-official analytical summary')}</div>${out()}`;}
  function search(natural){const examples=['Products below minimum stock',"Today's sales",'Invoices awaiting payment','Best selling products','Inactive customers','Profit this month','Most purchased supplier','Low stock items'];return `${notice()}<div class="report-card">${title(natural?'Natural Language Query':'Smart Search')}<div class="form-group"><label>Query</label><input id="aiSearchQuery" placeholder="${natural?'اسأل سؤالاً بلغة طبيعية':'Search ERP data naturally'}"></div><button class="btn btn-outline btn-sm" onclick="runAISmartSearch()">Search Read-only Snapshot</button><div class="ai-search-examples">${examples.map(x=>`<button class="btn btn-outline btn-sm" onclick="setAISearchExample('${x.replace(/'/g,"\\'")}')">${esc(x)}</button>`).join('')}</div></div>${out()}`;}
  function knowledge(){return `${notice()}<div class="ai-copilot-grid">${ns.KnowledgeCenter.articles.map(x=>`<div class="report-card">${title(x.title)}<div>${esc(x.answer)}</div></div>`).join('')}</div><div class="report-card" style="margin-top:14px">${title('Training Assistant & Feature Discovery')}${ns.TrainingAssistant.topics.map(x=>`<button class="btn btn-outline btn-sm" style="margin:4px" onclick="previewTrainingLesson('${x}')">${esc(x)}</button>`).join('')}</div>${out()}`;}
  function content(v){if(v==='business-assistant')return assistant();if(v==='sales-insights')return insight('sales');if(v==='inventory-insights')return insight('inventory');if(v==='accounting-insights')return insight('accounting');if(v==='purchase-insights')return insight('purchases');if(v==='customer-insights')return insight('customers');if(v==='supplier-insights')return insight('suppliers');if(v==='reports-assistant')return reports();if(v==='smart-search')return search(false);if(v==='natural-language-query')return search(true);if(v==='knowledge-center')return knowledge();return dashboard();}
  function renderAICopilotPage(view){const target=document.getElementById(`ai-copilot-${view}`);if(target)target.innerHTML=content(view);}function output(v){const target=document.querySelector('.page.active .ai-copilot-result');if(target)target.textContent=JSON.stringify(v,null,2);}
  async function refreshBusinessCopilot(){try{const v=await engine.refresh();renderAICopilotPage(document.querySelector('.page.active').id.replace('page-ai-copilot-',''));output(v);return v;}catch(e){output({error:String(e.message||e)});}}
  function askBusinessCopilot(){const v=engine.ask(document.getElementById('aiCopilotQuestion').value);renderAICopilotPage(document.querySelector('.page.active').id.replace('page-ai-copilot-',''));output(v);return v;}function runAISmartSearch(){const v=engine.search(document.getElementById('aiSearchQuery').value);output(v);return v;}function setAISearchExample(value){document.getElementById('aiSearchQuery').value=value;return runAISmartSearch();}function previewAIReport(type){const v=engine.report(type);output(v);return v;}function previewTrainingLesson(topic){const v=engine.lesson(topic);output(v);return v;}
  Object.assign(root,{renderAICopilotPage,refreshBusinessCopilot,askBusinessCopilot,runAISmartSearch,setAISearchExample,previewAIReport,previewTrainingLesson});root.OmniAICopilotUi=Object.freeze({version:'1.0.0',engine});
})(typeof globalThis!=='undefined'?globalThis:window);
