const assert=require('assert'),fs=require('fs'),path=require('path'),vm=require('vm');const root=path.resolve(__dirname,'..','..');let tests=0;const ok=(v,m)=>{assert.ok(v,m);tests+=1;};const eq=(a,b,m)=>{assert.strictEqual(a,b,m);tests+=1;};
const ids=['11111111-2222-4333-8444-555555555555','22222222-3333-4444-8555-666666666666'];let idIndex=0;const box=vm.createContext({console,Date,globalThis:{crypto:{randomUUID:()=>ids[idIndex++%ids.length]}}});box.window=box.globalThis;const modules=['OperationRegistry.js','ProductionModeConfiguration.js','OwnerAuthorizationGuard.js','ExecutionPolicyValidator.js','ConfirmationManager.js','ExecutionRequestBuilder.js','ExecutionQueue.js','SecureExecutionGateway.js','ExecutionVerifier.js','RollbackManager.js','FailureRecoveryEngine.js','ExecutionAuditBuilder.js','ProductionExecutionEngine.js'];modules.forEach(f=>new vm.Script(fs.readFileSync(path.join(__dirname,f),'utf8'),{filename:f}).runInContext(box));
async function run(){const ns=box.globalThis.OmniProductionExecution;[...modules,'productionExecutionUi.js','productionExecution.test.js','README.md'].forEach(f=>ok(fs.existsSync(path.join(__dirname,f)),`Missing ${f}`));
  eq(ns.OperationRegistry.definitions.length,10);['databaseInstallation','customerProvisioning','workspaceActivation','backup','restore','deployment','licenseActivation','supabaseSchemaInstallation','edgeFunctionDeployment','storageBucketCreation'].forEach(id=>ok(ns.OperationRegistry.get(id),`Missing ${id}`));
  const mode=ns.ProductionModeConfiguration.create();eq(mode.snapshot().enabled,false);eq(mode.snapshot().serverEnabled,false);eq(mode.snapshot().persistedInBrowser,false);eq(ns.OwnerAuthorizationGuard.validate({}).valid,false);eq(ns.OwnerAuthorizationGuard.validate({accessToken:'t',platformRole:'erp_owner',userId:'u'}).valid,true);
  const request=ns.ExecutionRequestBuilder.build('backup',{tenantId:'t1'},ids[0]);eq(request.stages.length,8);eq(request.executed,false);const phrase=ns.ConfirmationManager.phrase(request);eq(phrase,'EXECUTE:backup:t1:11111111-2222-4333-8444-555555555555');eq(ns.ConfirmationManager.validate(request,phrase).valid,true);eq(ns.ConfirmationManager.validate(request,'wrong').valid,false);
  const queue=ns.ExecutionQueue.create();queue.enqueue(request);eq(queue.list().length,1);eq(queue.pending().length,1);queue.replace(request.requestId,{status:'verified'});eq(queue.pending().length,0);
  const calls=[];const fetchImpl=async(_url,options)=>{const body=JSON.parse(options.body);calls.push({body,options});let value={};if(body.action==='status')value={mode:{enabled:false,serverEnabled:true,ownerVerified:true}};if(body.action==='enable-mode')value={mode:{enabled:true,serverEnabled:true,ownerVerified:true,enabledBy:'owner'}};if(body.action==='disable-mode')value={mode:{enabled:false,serverEnabled:true,ownerVerified:true}};if(body.action==='execute')value={executionId:body.requestId,operation:body.operation,tenantId:body.tenantId,result:{success:true,transactionSafe:true},verification:{passed:true},auditId:'audit-1',rollbackId:'rollback-1',durationMs:10,retrySupported:true,transactionSafe:true,audit:{executionId:body.requestId,who:'owner',result:'verified',rollbackId:'rollback-1',serverPersisted:true}};if(body.action==='rollback')value={executionId:body.executionId,rollbackId:body.rollbackId,verification:{passed:true}};return{ok:true,status:200,json:async()=>value};};
  const session={accessToken:'token',platformRole:'erp_owner',userId:'owner'};const engine=ns.ProductionExecutionEngine.create({fetchImpl,idFactory:()=>ids[0]});let state=await engine.connect({edgeFunctionUrl:'https://demo.supabase.co/functions/v1/omnistore-production-executor',anonKey:'anon-key'},session);eq(state.mode.enabled,false);eq(state.gateway.owner,true);eq(calls[0].body.action,'status');eq(calls[0].options.headers.Authorization,'Bearer token');eq(Object.prototype.hasOwnProperty.call(calls[0].options.headers,'service_role'),false);
  const blocked=engine.preview('backup',{tenantId:'t1'});eq(engine.enqueue(blocked,blocked.confirmationPhrase,session).valid,false);state=await engine.setMode(true,'ENABLE_PRODUCTION:owner');eq(state.mode.enabled,true);const preview=engine.preview('backup',{tenantId:'t1',estimatedDurationMs:100,writesExpected:true});eq(preview.executed,false);eq(preview.estimate.durationMs,100);eq(preview.confirmationPhrase.includes(preview.request.requestId),true);eq(engine.enqueue(preview,'wrong',session).valid,false);const queued=engine.enqueue(preview,preview.confirmationPhrase,session);eq(queued.valid,true);eq(queued.item.status,'pending');const executed=await engine.execute(queued.item.requestId);eq(executed.verification.valid,true);eq(executed.audit.serverPersisted,true);eq(executed.rollback.valid,true);eq(engine.snapshot().history.length,1);eq(engine.snapshot().queue[0].status,'verified');const rollback=await engine.rollback(executed.result,'ROLLBACK:rollback-1');eq(rollback.verification.passed,true);
  const verify=ns.ExecutionVerifier.validate({executionId:'e',result:{},verification:{passed:true},auditId:'a',rollbackId:'r'});eq(verify.valid,true);eq(ns.ExecutionVerifier.validate({}).valid,false);eq(ns.FailureRecoveryEngine.analyze({steps:[{status:'completed'},{status:'failed'}],rollbackId:'r'}).recommendation,'rollback');eq(ns.RollbackManager.preview({executionId:'e',rollbackId:'r'}).valid,true);
  const source=fs.readdirSync(__dirname).filter(f=>f.endsWith('.js')&&!f.endsWith('.test.js')).map(f=>fs.readFileSync(path.join(__dirname,f),'utf8')).join('\n');eq(/localStorage\s*\.|sessionStorage\s*\.|SUPABASE_DB_URL|SUPABASE_SERVICE_ROLE_KEY|service_role/i.test(source),false);eq(/postAccounting\s*\(|postInventory\s*\(/i.test(source),false);eq(/services[\\/](accounting|inventory|sales|purchases|pos)/i.test(source),false);
  const edgeDir=path.join(root,'supabase','functions','omnistore-production-executor'),edge=fs.readFileSync(path.join(edgeDir,'index.ts'),'utf8'),migration=fs.readFileSync(path.join(edgeDir,'migration.ts'),'utf8');['production_mode','execution_requests','rollback_points','execution_audit'].forEach(table=>ok(migration.includes(`omnistore_control.${table}`),`Missing ${table}`));ok(migration.includes('enabled boolean not null default false'));ok(migration.includes('enable row level security'));eq(/create policy .* (anon|authenticated)/i.test(migration),false);ok(edge.includes("platform_role !== 'erp_owner'"));ok(edge.includes("PRODUCTION_EXECUTION_ALLOWED') !== 'true'"));ok(edge.includes('EXECUTION_CONFIRMATION_MISMATCH'));ok(edge.includes('ROLLBACK_CONFIRMATION_MISMATCH'));ok(edge.includes("callExecutor(operation, 'prepare'"));ok(edge.includes("callExecutor(operation, 'execute'"));ok(edge.includes("callExecutor(operation, 'verify'"));ok(edge.includes("callExecutor(value.operation, 'rollback'"));ok(edge.includes("callExecutor(value.operation, 'verifyRollback'"));ok(edge.includes('idempotent: true'));eq(/Access-Control-Allow-Origin['"]?\s*[:,]\s*['"]\*/i.test(edge),false);eq(/eyJ[A-Za-z0-9._-]{20,}|sb_secret_[A-Za-z0-9._-]+|postgres(?:ql)?:\/\//i.test(edge+migration),false);
  const html=fs.readFileSync(path.join(root,'DigiTronics_v5.html'),'utf8');const pages=['execution-center','execution-queue','execution-history','pending-operations','rollback-manager','verification-center'];pages.forEach(p=>{ok(html.includes(`data-page="production-execution-${p}"`));ok(html.includes(`id="page-production-execution-${p}"`));ok(html.includes(`renderProductionExecutionPage('${p}')`));ok(html.includes(`'production-execution-${p}': 'manageUsers'`));});
  const ui=fs.readFileSync(path.join(__dirname,'productionExecutionUi.js'),'utf8');['PRODUCTION OFF','Enable Production','Disable Production','Preview','Confirm & Execute','Execution Report','Deployment Report','Provisioning Report','Verification Report','Rollback Report'].forEach(label=>ok(ui.includes(label),`Missing ${label}`));ok(ui.includes('root.prompt'));ok(ui.includes('root.confirm'));
  return{tests,productionLayerReadiness:100,operations:10,realExecutionsDuringTests:0,rollbackSimulation:true,verificationSimulation:true,defaultProductionMode:'OFF'};
}
if(require.main===module)run().then(v=>console.log(JSON.stringify(v,null,2))).catch(e=>{console.error(e);process.exitCode=1;});module.exports={run};
