(function(root){
  'use strict';
  const ns=root.OmniPlatformOperations;
  const sample={customers:[],health:[],errors:[],updates:[],snapshots:[]};
  const engine=ns.PlatformOperationsEngine.create({provider:{readSnapshot:async()=>sample}});
  const esc=v=>String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const row=(a,b)=>`<div class="platform-ops-row"><span>${esc(a)}</span><strong>${esc(b)}</strong></div>`;
  const notice=()=>'<div class="alert alert-info"><strong>Platform Operations — Read Only.</strong> لا يتم تنفيذ Backup أو Restore أو Update. تعرض الصفحة Snapshot مراقبة فقط.</div>';
  const out=()=>'<pre class="platform-ops-result">No platform operation has run.</pre>';
  function dashboard(){const d=engine.snapshot().dashboard;return `${notice()}<div class="platform-ops-actions"><button class="btn btn-outline btn-sm" onclick="refreshPlatformOperations()">Refresh Monitoring Snapshot</button></div><div class="platform-ops-grid">${Object.entries(d).map(([k,v])=>`<div class="report-card">${row(k,typeof v==='object'?JSON.stringify(v):v)}</div>`).join('')}</div>${out()}`;}
  function monitoring(){const s=engine.snapshot();return `${notice()}<div class="platform-ops-actions"><button class="btn btn-outline btn-sm" onclick="refreshPlatformOperations()">Refresh Monitoring Snapshot</button></div><div class="overflow-x"><table class="data-table"><thead><tr><th>Workspace</th><th>CPU</th><th>Memory</th><th>Storage</th><th>Database</th><th>API</th><th>Edge</th><th>Realtime</th><th>Connection</th></tr></thead><tbody>${s.health.length?s.health.map(h=>`<tr><td>${esc(h.businessName)}</td><td>${h.cpuUsage}%</td><td>${h.memoryUsage}%</td><td>${h.storageUsage}%</td><td>${esc(h.databaseSize)}</td><td>${esc(h.apiHealth)}</td><td>${esc(h.edgeFunctionHealth)}</td><td>${esc(h.realtimeHealth)}</td><td>${esc(h.connectionStatus)}</td></tr>`).join(''):'<tr><td colspan="9">No monitoring snapshot loaded.</td></tr>'}</tbody></table></div>${out()}`;}
  function backup(){return `${notice()}<div class="report-card"><div class="table-title">Backup Center</div><div class="form-grid"><div class="form-group"><label>Tenant ID</label><input id="opsTenantId"></div><div class="form-group"><label>Frequency</label><select id="opsBackupFrequency"><option>daily</option><option>weekly</option><option>monthly</option></select></div><div class="form-group"><label>Retention Days</label><input id="opsRetention" type="number" min="1" value="30"></div></div><div class="platform-ops-actions"><button class="btn btn-outline btn-sm" onclick="previewPlatformBackup('scheduled')">Scheduled Backup Plan</button><button class="btn btn-outline btn-sm" onclick="previewPlatformBackup('manual')">Manual Backup Preview</button><button class="btn btn-outline btn-sm" onclick="previewPlatformBackup('restore')">Restore Preview</button></div>${row('Execution','Disabled in Phase 29')}${row('Snapshot Browser','Read-only metadata')}${row('Backup Verification','Checksum preview')}</div>${out()}`;}
  function update(){return `${notice()}<div class="report-card"><div class="table-title">Update Center</div><div class="form-grid"><div class="form-group"><label>Tenant ID</label><input id="updateTenantId"></div><div class="form-group"><label>Current Version</label><input id="currentPlatformVersion" value="1.0.0"></div><div class="form-group"><label>Available Version</label><input id="availablePlatformVersion" value="1.1.0"></div><div class="form-group"><label>Migration Version</label><input id="platformMigrationVersion"></div></div><div class="platform-ops-actions"><button class="btn btn-outline btn-sm" onclick="previewPlatformUpdate()">Update Preview</button><button class="btn btn-outline btn-sm" onclick="previewPlatformRollback()">Rollback Preview</button></div>${row('Update execution','Disabled')}${row('Release Notes','Provider snapshot')}${row('Customer Update Status','Read-only')}</div>${out()}`;}
  function errors(){const s=engine.snapshot();return `${notice()}<div class="report-card"><div class="table-title">Error Dashboard</div>${Object.entries(ns.ErrorCenter.summary(s.errors)).map(([k,v])=>row(k,v)).join('')}${row('Total',s.errors.length)}</div>${out()}`;}
  function health(){const s=engine.snapshot();return `${notice()}<div class="platform-ops-grid">${s.health.length?s.health.map(h=>`<div class="report-card"><div class="table-title">${esc(h.businessName||h.tenantId)}</div>${row('Health Score',`${ns.HealthMonitor.score(h)}%`)}${row('Workspace',h.workspaceHealth)}${row('API',h.apiHealth)}${row('Storage',h.storageHealth)}${row('Version',h.version)}${row('Migration',h.migrationVersion)}</div>`).join(''):'<div class="report-card">No workspace health loaded.</div>'}</div>${out()}`;}
  function content(view){if(view==='monitoring-center')return monitoring();if(view==='backup-center')return backup();if(view==='update-center')return update();if(view==='error-dashboard')return errors();if(view==='customer-health')return health();return dashboard();}
  function renderPlatformOperationsPage(view){const target=document.getElementById(`platform-ops-${view}`);if(target)target.innerHTML=content(view);}
  function output(v){const target=document.querySelector('.page.active .platform-ops-result');if(target)target.textContent=JSON.stringify(v,null,2);}
  async function refreshPlatformOperations(){try{const v=await engine.refresh();renderPlatformOperationsPage(document.querySelector('.page.active').id.replace('page-',''));output(v);return v;}catch(e){output({error:String(e.message||e)});}}
  function previewPlatformBackup(kind){const v=engine.backupPreview(kind,{tenantId:document.getElementById('opsTenantId').value,frequency:document.getElementById('opsBackupFrequency').value,retentionDays:Number(document.getElementById('opsRetention').value)});output(v);return v;}
  function updateInput(){return{tenantId:document.getElementById('updateTenantId').value,currentVersion:document.getElementById('currentPlatformVersion').value,availableVersion:document.getElementById('availablePlatformVersion').value,migrationVersion:document.getElementById('platformMigrationVersion').value,releaseNotes:[]};}
  function previewPlatformUpdate(){const v=engine.updatePreview(updateInput());output(v);return v;}
  function previewPlatformRollback(){const v=engine.rollbackPreview(engine.updatePreview(updateInput()));output(v);return v;}
  Object.assign(root,{renderPlatformOperationsPage,refreshPlatformOperations,previewPlatformBackup,previewPlatformUpdate,previewPlatformRollback});
  root.OmniPlatformOperationsUi=Object.freeze({version:'1.0.0',engine});
})(typeof globalThis!=='undefined'?globalThis:window);
