/**
 * Lettercross - pure rules. NO DOM, NO React, NO Phaser (games/logic-is-pure.test.ts).
 *
 * A crossword tile game. Lay letters on a grid, every run of two or more must
 * be a word, score by letter value and premium square.
 *
 * WHAT IS DELIBERATELY NOT THE GAME YOU ARE THINKING OF, and why it is in the
 * code rather than in a lawyer's note: game MECHANICS are not copyrightable
 * (17 U.S.C. 102(b)), but a clone's overall commercial impression can still be
 * actionable, and the 2008 Scrabulous settlement had its authors change the
 * tiles per turn, at least half the letter values, at least half the letter
 * distribution, the premium-square pattern and the centre star. So:
 *
 *   board        9 x 9, not 15 x 15
 *   rack         8 tiles at the middle level, not 7
 *   values       14 of 26 letters differ (pinned by logic.test.ts)
 *   distribution its own, built from English letter frequency
 *   premiums     a diamond and a ring, generated by a RULE below - no X, no
 *                edge-to-edge diagonals
 *   centre       a plain start square with NO multiplier and no star
 *   wilds        four, not two - twice what the classic gives you
 *
 * See NOTICE.md for the word-list provenance, which is the other half of this.
 */
import { WORDS } from "./words";
import { BOX_INDICES } from "./boxes";
import { CELLS, SIZE, W, at, boardAt, colOf, rowOf, type Board, type Cell } from "./grid";

export { SIZE, W, CELLS, boardAt, at, type Board, type Cell };

/**
 * NINE, and it moved 11 -> 9 on 2026-08-24 for a reason that is not aesthetic.
 *
 * The board carries a one-cell ring of prize boxes outside it, and the ring has
 * to come from somewhere. Measured on the artifact at 390px: with the ring added
 * to an 11-wide board the cell falls to 28.2px, the smallest tap target in this
 * catalogue - against a 44px generic floor and a 64px `--tap-kids`. At nine the
 * whole stage is the width the board alone used to be and the cell is back to
 * 33.3px, so the ring costs the player nothing.
 *
 * It is also further from the famous 15 x 15 than it was, which the header's
 * distinctiveness list depends on, and it takes away squares an eight-tile rack
 * was never going to reach.
 *
 * It lives in `grid.ts` now and is re-exported here, so the forty places that
 * import it from this module still do. See that file for why the index space is
 * the whole W x W stage rather than the SIZE x SIZE board.
 */
/** The middle level's rack. `rackFor` is the real answer; this is medium's. */
export const RACK = 8;

export type Level = "easy" | "medium" | "hard";
/** A tile in hand. "?" is a wild; it becomes a letter only when placed. */
export type Tile = string;
export type Placement = { readonly index: number; readonly letter: string; readonly wild: boolean };

export type State = {
  readonly level: Level;
  readonly board: Board;
  readonly rack: readonly Tile[];
  readonly bag: readonly Tile[];
  readonly score: number;
  readonly played: number;
};

/**
 * Letter values. Frequency-shaped, and 14 of the 26 differ from the famous
 * board's - `logic.test.ts` pins that count so a later "tidy-up" cannot quietly
 * restore them.
 */
export const LETTER_VALUE: Readonly<Record<string, number>> = {
  a: 1, b: 4, c: 2, d: 2, e: 1, f: 4, g: 3, h: 2, i: 1, j: 9, k: 6, l: 2, m: 4,
  n: 1, o: 1, p: 2, q: 12, r: 1, s: 1, t: 1, u: 2, v: 5, w: 4, x: 9, y: 4, z: 12,
};

const COUNTS: Readonly<Record<string, number>> = {
  e: 10, a: 7, i: 7, o: 7, n: 5, r: 5, t: 5, s: 5, l: 5, u: 4, d: 4, c: 3, h: 3,
  m: 2, g: 2, p: 2, b: 2, y: 2, f: 2, w: 2, v: 1, k: 1, j: 1, x: 1, q: 1, z: 1,
};

/** Four wilds - twice the usual two. A wild scores 0 but spells any letter. */
export const WILDS = 4;

export const BAG: readonly Tile[] = (() => {
  const out: Tile[] = [];
  for (const [ch, n] of Object.entries(COUNTS)) for (let i = 0; i < n; i++) out.push(ch);
  for (let i = 0; i < WILDS; i++) out.push("?");
  return out;
})();
export const TOTAL_TILES = BAG.length;

/** Easy hands you more letters to work with. It never changes the DICTIONARY. */
export function rackFor(level: Level): number {
  return level === "easy" ? 9 : level === "hard" ? 7 : 8;
}

/** The score board a level records against - the scales are not comparable. */
export function bestLevel(level: Level): string {
  return level;
}

function shuffle<T>(xs: readonly T[], rng: () => number): T[] {
  const a = [...xs];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(rng() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

export function newGame(level: Level, rng: () => number = Math.random): State {
  const bag = shuffle(BAG, rng);
  const n = rackFor(level);
  return {
    level,
    board: Array<Cell>(CELLS).fill(null),
    rack: bag.slice(0, n),
    bag: bag.slice(n),
    score: 0,
    played: 0,
  };
}

/** Refill a rack from the bag. Returns the new rack and what is left. */
export function draw(rack: readonly Tile[], bag: readonly Tile[], want: number) {
  const need = Math.max(0, want - rack.length);
  return { rack: [...rack, ...bag.slice(0, need)], bag: bag.slice(need) };
}

/**
 * WHICH SQUARES A TILE MAY GO ON: the inner SIZE x SIZE board, plus the twelve
 * prize boxes in the ring, and nothing else. The rest of the ring - the four
 * corners and the gaps between boxes - is stage, not board.
 *
 * It is what makes the prize squares need no special case anywhere else. A word
 * runs off the edge of the board into a box exactly the way it runs from one
 * board square to the next, because a box IS a square; and it cannot run ALONG
 * the ring, because the cells either side of a box are dead and a run stops at
 * an empty square. `boxes-are-in-line.test.ts` pins that no two boxes are
 * adjacent, which is the assumption underneath that second half.
 */
export const PLAYABLE: readonly boolean[] = (() => {
  const ok = Array<boolean>(CELLS).fill(false);
  for (let r = 0; r < SIZE; r++) for (let c = 0; c < SIZE; c++) ok[boardAt(r, c)] = true;
  for (const i of BOX_INDICES) ok[i] = true;
  return ok;
})();

export type Scored = { readonly word: string; readonly score: number };
export type Verdict =
  | { readonly ok: true; readonly words: readonly Scored[]; readonly total: number }
  | { readonly ok: false; readonly reason: "line" | "gap" | "word" | "empty" | "off" };

/** Walk a filled run through `index` along a step, and return it with its cells. */
function runThrough(board: Board, index: number, step: number): number[] {
  const sameLine = (a: number, b: number) =>
    step === 1 ? rowOf(a) === rowOf(b) : colOf(a) === colOf(b);
  let start = index;
  while (start - step >= 0 && sameLine(start, start - step) && board[start - step]) start -= step;
  const run: number[] = [];
  for (let i = start; i < CELLS && board[i] && (i === start || sameLine(i, i - step)); i += step) run.push(i);
  return run;
}

export function validate(board: Board, placements: readonly Placement[]): Verdict {
  if (placements.length === 0) return { ok: false, reason: "empty" };
  if (placements.some((p) => board[p.index] !== null)) return { ok: false, reason: "line" };
  if (placements.some((p) => !PLAYABLE[p.index])) return { ok: false, reason: "off" };

  const rows = new Set(placements.map((p) => rowOf(p.index)));
  const cols = new Set(placements.map((p) => colOf(p.index)));
  const horizontal = rows.size === 1;
  const vertical = cols.size === 1;
  if (!horizontal && !vertical) return { ok: false, reason: "line" };

  // The merged board: what it would look like if this play stood.
  const next: Cell[] = [...board];
  for (const p of placements) next[p.index] = { letter: p.letter.toLowerCase(), wild: p.wild };

  // Contiguity along the main axis, counting tiles already on the board.
  // Checked BEFORE the start-square rule: two tiles either side of the centre
  // with a hole between them is a gap, and calling that "you missed the start"
  // would send the player to fix the wrong thing.
  const step = horizontal ? 1 : W;
  const idxs = placements.map((p) => p.index).sort((a, b) => a - b);
  for (let i = idxs[0]; i <= idxs[idxs.length - 1]; i += step) if (!next[i]) return { ok: false, reason: "gap" };

  // A WORD GOES ANYWHERE. There is deliberately no start square and no
  // requirement to touch what is already down - operator's call, 2026-08-24:
  // "user should put any word they want anywhere".
  //
  // What survives is only what a WORD is: it lies in one line, it has no holes
  // in it, and it is a real word. Those three are the game. A centre-start and
  // a connection rule are the borrowed part, and dropping them is what makes
  // this a placing game rather than a tighter one.
  //
  // Cross-words are still checked, because two words that happen to meet must
  // both read - that is not a connection RULE, it is what a grid means.

  const seen = new Set<string>();
  const words: Scored[] = [];

  const collect = (run: number[]) => {
    if (run.length < 2) return true;
    const key = run.join(",");
    if (seen.has(key)) return true;
    seen.add(key);
    const word = run.map((i) => next[i]!.letter).join("");
    if (!WORDS.has(word)) return false;
    // A word is worth its letters. No premium squares, no multipliers -
    // operator's call, 2026-08-24: "i dont need the bonus or special boxes".
    let sum = 0;
    for (const i of run) {
      const cell = next[i]!;
      sum += cell.wild ? 0 : (LETTER_VALUE[cell.letter] ?? 0);
    }
    words.push({ word, score: sum });
    return true;
  };

  // The main word along the axis of play, then every cross-word a new tile made.
  if (!collect(runThrough(next, idxs[0], step))) return { ok: false, reason: "word" };
  for (const p of placements) if (!collect(runThrough(next, p.index, step === 1 ? W : 1))) return { ok: false, reason: "word" };

  // A PLAY MUST MAKE A WORD. With the start square and the touch rule gone
  // (2026-08-24) nothing else stops a single tile being dropped on an empty
  // square: `collect` passes any run shorter than two letters, so one tile
  // formed no word, broke no rule, and was accepted for zero points - a way to
  // empty the bag rather than a turn. Measured the moment those guards came
  // out: `{"ok":true,"words":[],"total":0}`.
  //
  // "Any word anywhere" is the freedom. A word is still the price.
  if (words.length === 0) return { ok: false, reason: "word" };

  return { ok: true, words, total: words.reduce((n, w) => n + w.score, 0) };
}

/**
 * Take a turn. Returns a NEW state and never touches the one it was handed -
 * `useGameSession` snapshots this object, and a mutated board would be written
 * to disk under the previous turn's score.
 *
 * Tiles are spent by matching letter, and a wild spends a "?". A placement
 * whose letter is not in the rack spends an arbitrary tile instead of throwing:
 * the renderer only ever builds placements from the rack, and a logic core that
 * can throw mid-turn loses the whole board rather than one illegal move.
 */
export function apply(state: State, placements: readonly Placement[]): State {
  const v = validate(state.board, placements);
  if (!v.ok) return state;

  const board: Cell[] = [...state.board];
  for (const p of placements) board[p.index] = { letter: p.letter.toLowerCase(), wild: p.wild };

  const rack = [...state.rack];
  for (const p of placements) {
    const want = p.wild ? "?" : p.letter.toLowerCase();
    const at = rack.indexOf(want);
    rack.splice(at >= 0 ? at : 0, 1);
  }

  const filled = draw(rack, state.bag, rackFor(state.level));
  return {
    ...state,
    board,
    rack: filled.rack,
    bag: filled.bag,
    score: state.score + v.total,
    played: state.played + 1,
  };
}

/** The run ends when there is nothing left to play with. */
export function isOver(state: State): boolean {
  return state.bag.length === 0 && state.rack.length === 0;
}
